// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Player;

public sealed partial class CheckNgWordRequest : IMessage<global::App.Protobuf.Player.CheckNgWordRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Player.CheckNgWordRequest> _parser = new(() => new global::App.Protobuf.Player.CheckNgWordRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Player.CheckNgWordRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CheckNgWordRequest()
    {
    }

    public CheckNgWordRequest(CheckNgWordRequest other) : this()
    {
        word_ = other.word_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CheckNgWordRequest Clone() => new(this);

    public const int WordFieldNumber = 1;
    private string word_ = "";
    public string Word
    {
        get => word_;
        set => word_ = value ?? "";
    }

    public override bool Equals(object? other) => Equals(other as CheckNgWordRequest);

    public bool Equals(CheckNgWordRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Word, other.Word)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Word.Length != 0) hash ^= Word.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Word.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(Word);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Word.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(Word);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CheckNgWordRequest? other)
    {
        if (other == null) return;
        if (other.Word.Length != 0) Word = other.Word;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Word = input.ReadString();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
