// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Player;

public sealed partial class RegisterConnectionRequest : IMessage<global::App.Protobuf.Player.RegisterConnectionRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Player.RegisterConnectionRequest> _parser = new(() => new global::App.Protobuf.Player.RegisterConnectionRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Player.RegisterConnectionRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public RegisterConnectionRequest() { }

    public RegisterConnectionRequest(RegisterConnectionRequest other) : this()
    {
        password_ = other.password_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public RegisterConnectionRequest Clone() => new(this);

    public const int PasswordFieldNumber = 1;
    private string password_ = "";
    public string Password
    {
        get => password_;
        set => password_ = value ?? "";
    }

    public override bool Equals(object? other) => Equals(other as RegisterConnectionRequest);

    public bool Equals(RegisterConnectionRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return Password == other.Password && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Password.Length != 0) hash ^= Password.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Password.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(Password);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Password.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(Password);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(RegisterConnectionRequest? other)
    {
        if (other == null) return;
        if (other.Password.Length != 0) Password = other.Password;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) Password = input.ReadString();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
