// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Player;

public sealed partial class RegisterDeviceForConnectedPlayerResponse : IMessage<global::App.Protobuf.Player.RegisterDeviceForConnectedPlayerResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Player.RegisterDeviceForConnectedPlayerResponse> _parser = new(() => new global::App.Protobuf.Player.RegisterDeviceForConnectedPlayerResponse());
    private UnknownFieldSet? _unknownFields;
    public static MessageParser<global::App.Protobuf.Player.RegisterDeviceForConnectedPlayerResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public RegisterDeviceForConnectedPlayerResponse() { }
    public RegisterDeviceForConnectedPlayerResponse(RegisterDeviceForConnectedPlayerResponse other) : this()
    {
        credential_ = other.credential_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }
    public RegisterDeviceForConnectedPlayerResponse Clone() => new(this);

    public const int CredentialFieldNumber = 1;
    private global::App.Protobuf.Entity.PlayerCredential? credential_;
    public global::App.Protobuf.Entity.PlayerCredential? Credential { get => credential_; set => credential_ = value; }

    public override bool Equals(object? other) => Equals(other as RegisterDeviceForConnectedPlayerResponse);
    public bool Equals(RegisterDeviceForConnectedPlayerResponse? other) =>
        !ReferenceEquals(other, null) &&
        (ReferenceEquals(other, this) ||
         (Equals(Credential, other.Credential) && Equals(_unknownFields, other._unknownFields)));
    public override int GetHashCode()
    {
        var hash = 1;
        if (Credential != null) hash ^= Credential.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }
    public override string ToString() => base.ToString() ?? string.Empty;
    public void WriteTo(CodedOutputStream output)
    {
        if (Credential != null) { output.WriteRawTag(0x0A); output.WriteMessage(Credential); }
        _unknownFields?.WriteTo(output);
    }
    public int CalculateSize()
    {
        var size = Credential == null ? 0 : CodedOutputStream.ComputeTagSize(1) + CodedOutputStream.ComputeMessageSize(Credential);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }
    public void MergeFrom(RegisterDeviceForConnectedPlayerResponse? other)
    {
        if (other == null) return;
        if (other.Credential != null)
        {
            if (Credential == null) Credential = other.Credential.Clone();
            else Credential.MergeFrom(other.Credential);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }
    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u)
            {
                Credential ??= new global::App.Protobuf.Entity.PlayerCredential();
                input.ReadMessage(Credential);
            }
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
