// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Player;

public sealed partial class RegisterRequest : IMessage<global::App.Protobuf.Player.RegisterRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Player.RegisterRequest> _parser = new(() => new global::App.Protobuf.Player.RegisterRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Player.RegisterRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public RegisterRequest()
    {
    }

    public RegisterRequest(RegisterRequest other) : this()
    {
        initialDataGroup_ = other.initialDataGroup_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public RegisterRequest Clone() => new(this);

    public const int InitialDataGroupFieldNumber = 1;
    private string initialDataGroup_ = "";
    public string InitialDataGroup
    {
        get => initialDataGroup_;
        set => initialDataGroup_ = value ?? "";
    }

    public override bool Equals(object? other) => Equals(other as RegisterRequest);

    public bool Equals(RegisterRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(InitialDataGroup, other.InitialDataGroup)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (InitialDataGroup.Length != 0) hash ^= InitialDataGroup.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (InitialDataGroup.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(InitialDataGroup);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (InitialDataGroup.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(InitialDataGroup);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(RegisterRequest? other)
    {
        if (other == null) return;
        if (other.InitialDataGroup.Length != 0) InitialDataGroup = other.InitialDataGroup;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    InitialDataGroup = input.ReadString();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
