// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Player;

public sealed partial class RegisterResponse : IMessage<global::App.Protobuf.Player.RegisterResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Player.RegisterResponse> _parser = new(() => new global::App.Protobuf.Player.RegisterResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Player.RegisterResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public RegisterResponse()
    {
    }

    public RegisterResponse(RegisterResponse other) : this()
    {
        credential_ = other.credential_?.Clone();
        profileId_ = other.profileId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public RegisterResponse Clone() => new(this);

    public const int CredentialFieldNumber = 1;
    private global::App.Protobuf.Entity.PlayerCredential? credential_;
    public global::App.Protobuf.Entity.PlayerCredential? Credential
    {
        get => credential_;
        set => credential_ = value;
    }

    public const int ProfileIdFieldNumber = 2;
    private long profileId_ = 0;
    public long ProfileId
    {
        get => profileId_;
        set => profileId_ = value;
    }

    public override bool Equals(object? other) => Equals(other as RegisterResponse);

    public bool Equals(RegisterResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Credential, other.Credential)) return false;
        if (!Equals(ProfileId, other.ProfileId)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Credential != null) hash ^= Credential.GetHashCode();
        if (ProfileId != 0) hash ^= ProfileId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Credential != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(Credential);
        }
        if (ProfileId != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(ProfileId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Credential != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(Credential);
        }
        if (ProfileId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(ProfileId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(RegisterResponse? other)
    {
        if (other == null) return;
        if (other.Credential != null)
        {
            if (Credential == null)
                Credential = other.Credential.Clone();
            else
                Credential.MergeFrom(other.Credential);
        }
        if (other.ProfileId != 0) ProfileId = other.ProfileId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Credential ??= new global::App.Protobuf.Entity.PlayerCredential();
                    input.ReadMessage(Credential);
                    break;
                case 16u:
                    ProfileId = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
