// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Player;

public sealed partial class RemovePlayerDataRequest : IMessage<global::App.Protobuf.Player.RemovePlayerDataRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Player.RemovePlayerDataRequest> _parser = new(() => new global::App.Protobuf.Player.RemovePlayerDataRequest());
    private UnknownFieldSet? _unknownFields;
    public static MessageParser<global::App.Protobuf.Player.RemovePlayerDataRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;
    public RemovePlayerDataRequest() { }
    public RemovePlayerDataRequest(RemovePlayerDataRequest other) => _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    public RemovePlayerDataRequest Clone() => new(this);
    public override bool Equals(object? other) => Equals(other as RemovePlayerDataRequest);
    public bool Equals(RemovePlayerDataRequest? other) => !ReferenceEquals(other, null) && (ReferenceEquals(other, this) || Equals(_unknownFields, other._unknownFields));
    public override int GetHashCode() => _unknownFields?.GetHashCode() ?? 1;
    public override string ToString() => base.ToString() ?? string.Empty;
    public void WriteTo(CodedOutputStream output) => _unknownFields?.WriteTo(output);
    public int CalculateSize() => _unknownFields?.CalculateSize() ?? 0;
    public void MergeFrom(RemovePlayerDataRequest? other)
    {
        if (other == null) return;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }
    public void MergeFrom(CodedInputStream input)
    {
        while (input.ReadTag() != 0)
            _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
    }
}
