// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Gacha;

public sealed partial class HistoryResponse : IMessage<global::App.Protobuf.Gacha.HistoryResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Gacha.HistoryResponse> _parser = new(() => new global::App.Protobuf.Gacha.HistoryResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Gacha.HistoryResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public HistoryResponse()
    {
    }

    public HistoryResponse(HistoryResponse other) : this()
    {
        history_ = other.history_.Clone();
        executionHistory_ = other.executionHistory_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public HistoryResponse Clone() => new(this);

    public const int HistoryFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.GachaHistory> _repeated_history_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.GachaHistory.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.GachaHistory> history_ = new();
    public RepeatedField<global::App.Protobuf.Entity.GachaHistory> History => history_;

    public const int ExecutionHistoryFieldNumber = 2;
    private static readonly FieldCodec<global::App.Protobuf.Entity.GachaExecutionHistory> _repeated_executionHistory_codec = FieldCodec.ForMessage(18u, global::App.Protobuf.Entity.GachaExecutionHistory.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.GachaExecutionHistory> executionHistory_ = new();
    public RepeatedField<global::App.Protobuf.Entity.GachaExecutionHistory> ExecutionHistory => executionHistory_;

    public override bool Equals(object? other) => Equals(other as HistoryResponse);

    public bool Equals(HistoryResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!history_.Equals(other.history_)) return false;
        if (!executionHistory_.Equals(other.executionHistory_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= history_.GetHashCode();
        hash ^= executionHistory_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        history_.WriteTo(output, _repeated_history_codec);
        executionHistory_.WriteTo(output, _repeated_executionHistory_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += history_.CalculateSize(_repeated_history_codec);
        size += executionHistory_.CalculateSize(_repeated_executionHistory_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(HistoryResponse? other)
    {
        if (other == null) return;
        history_.Add(other.history_);
        executionHistory_.Add(other.executionHistory_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    history_.AddEntriesFrom(input, _repeated_history_codec);
                    break;
                case 18u:
                    executionHistory_.AddEntriesFrom(input, _repeated_executionHistory_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
