// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Gacha;

public sealed partial class HistoryRequest : IMessage<global::App.Protobuf.Gacha.HistoryRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Gacha.HistoryRequest> _parser = new(() => new global::App.Protobuf.Gacha.HistoryRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Gacha.HistoryRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public HistoryRequest()
    {
    }

    public HistoryRequest(HistoryRequest other) : this()
    {
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public HistoryRequest Clone() => new(this);

    public override bool Equals(object? other) => Equals(other as HistoryRequest);

    public bool Equals(HistoryRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(HistoryRequest? other)
    {
        if (other == null) return;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
            _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
    }
}
