// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Live;

public sealed partial class StartFreeRequest : IMessage<global::App.Protobuf.Live.StartFreeRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Live.StartFreeRequest> _parser = new(() => new global::App.Protobuf.Live.StartFreeRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Live.StartFreeRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public StartFreeRequest()
    {
    }

    public StartFreeRequest(StartFreeRequest other) : this()
    {
        musicId_ = other.musicId_;
        difficulty_ = other.difficulty_;
        boost_ = other.boost_;
        deckId_ = other.deckId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public StartFreeRequest Clone() => new(this);

    public const int MusicIdFieldNumber = 1;
    private long musicId_;
    public long MusicId
    {
        get => musicId_;
        set => musicId_ = value;
    }

    public const int DifficultyFieldNumber = 2;
    private int difficulty_;
    public int Difficulty
    {
        get => difficulty_;
        set => difficulty_ = value;
    }

    public const int BoostFieldNumber = 3;
    private int boost_;
    public int Boost
    {
        get => boost_;
        set => boost_ = value;
    }

    public const int DeckIdFieldNumber = 4;
    private int deckId_;
    public int DeckId
    {
        get => deckId_;
        set => deckId_ = value;
    }

    public override bool Equals(object? other) => Equals(other as StartFreeRequest);

    public bool Equals(StartFreeRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (MusicId != other.MusicId) return false;
        if (Difficulty != other.Difficulty) return false;
        if (Boost != other.Boost) return false;
        if (DeckId != other.DeckId) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (MusicId != 0L) hash ^= MusicId.GetHashCode();
        if (Difficulty != 0) hash ^= Difficulty.GetHashCode();
        if (Boost != 0) hash ^= Boost.GetHashCode();
        if (DeckId != 0) hash ^= DeckId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (MusicId != 0L)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(MusicId);
        }
        if (Difficulty != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Difficulty);
        }
        if (Boost != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(Boost);
        }
        if (DeckId != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt32(DeckId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (MusicId != 0L)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(MusicId);
        }
        if (Difficulty != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Difficulty);
        }
        if (Boost != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(Boost);
        }
        if (DeckId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt32Size(DeckId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(StartFreeRequest? other)
    {
        if (other == null) return;
        if (other.MusicId != 0L) MusicId = other.MusicId;
        if (other.Difficulty != 0) Difficulty = other.Difficulty;
        if (other.Boost != 0) Boost = other.Boost;
        if (other.DeckId != 0) DeckId = other.DeckId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    MusicId = input.ReadInt64();
                    break;
                case 16u:
                    Difficulty = input.ReadInt32();
                    break;
                case 24u:
                    Boost = input.ReadInt32();
                    break;
                case 32u:
                    DeckId = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
