// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleRankUpReward;

public sealed partial class GetCircleRankUpRewardReceivedResponse : IMessage<global::App.Protobuf.CircleRankUpReward.GetCircleRankUpRewardReceivedResponse>
{
    private static readonly MessageParser<global::App.Protobuf.CircleRankUpReward.GetCircleRankUpRewardReceivedResponse> _parser = new(() => new global::App.Protobuf.CircleRankUpReward.GetCircleRankUpRewardReceivedResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.CircleRankUpReward.GetCircleRankUpRewardReceivedResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetCircleRankUpRewardReceivedResponse() { }

    public GetCircleRankUpRewardReceivedResponse(GetCircleRankUpRewardReceivedResponse other) : this()
    {
        circleRankUpRewardReceived_ = other.circleRankUpRewardReceived_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetCircleRankUpRewardReceivedResponse Clone() => new(this);

    public const int CircleRankUpRewardReceivedFieldNumber = 1;
    private global::App.Protobuf.Entity.CircleRankUpRewardReceived? circleRankUpRewardReceived_;
    public global::App.Protobuf.Entity.CircleRankUpRewardReceived? CircleRankUpRewardReceived
    {
        get => circleRankUpRewardReceived_;
        set => circleRankUpRewardReceived_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GetCircleRankUpRewardReceivedResponse);

    public bool Equals(GetCircleRankUpRewardReceivedResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(CircleRankUpRewardReceived, other.CircleRankUpRewardReceived)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (CircleRankUpRewardReceived != null) hash ^= CircleRankUpRewardReceived.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (CircleRankUpRewardReceived != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(CircleRankUpRewardReceived);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (CircleRankUpRewardReceived != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(CircleRankUpRewardReceived);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetCircleRankUpRewardReceivedResponse? other)
    {
        if (other == null) return;
        if (other.CircleRankUpRewardReceived != null)
        {
            if (CircleRankUpRewardReceived == null)
                CircleRankUpRewardReceived = other.CircleRankUpRewardReceived.Clone();
            else
                CircleRankUpRewardReceived.MergeFrom(other.CircleRankUpRewardReceived);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u)
            {
                CircleRankUpRewardReceived ??= new global::App.Protobuf.Entity.CircleRankUpRewardReceived();
                input.ReadMessage(CircleRankUpRewardReceived);
            }
            else
            {
                _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
        }
    }
}
