// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleJoinRequest;

public sealed partial class CircleJoinReqResponse : IMessage<global::App.Protobuf.CircleJoinRequest.CircleJoinReqResponse>
{
    private static readonly MessageParser<global::App.Protobuf.CircleJoinRequest.CircleJoinReqResponse> _parser = new(() => new global::App.Protobuf.CircleJoinRequest.CircleJoinReqResponse());
    private UnknownFieldSet? _unknownFields;
    private int _hasBits0;

    public static MessageParser<global::App.Protobuf.CircleJoinRequest.CircleJoinReqResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CircleJoinReqResponse() { }

    public CircleJoinReqResponse(CircleJoinReqResponse other) : this()
    {
        _hasBits0 = other._hasBits0;
        circleId_ = other.circleId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CircleJoinReqResponse Clone() => new(this);

    public const int CircleIdFieldNumber = 1;
    private static readonly ulong CircleIdDefaultValue = 0;
    private ulong circleId_;
    public ulong CircleId
    {
        get => HasCircleId ? circleId_ : CircleIdDefaultValue;
        set
        {
            _hasBits0 |= 1;
            circleId_ = value;
        }
    }
    public bool HasCircleId => (_hasBits0 & 1) != 0;
    public void ClearCircleId() => _hasBits0 &= ~1;

    public override bool Equals(object? other) => Equals(other as CircleJoinReqResponse);

    public bool Equals(CircleJoinReqResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (HasCircleId != other.HasCircleId) return false;
        if (HasCircleId && !Equals(CircleId, other.CircleId)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (HasCircleId) hash ^= CircleId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (HasCircleId)
        {
            output.WriteRawTag(0x08);
            output.WriteUInt64(CircleId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (HasCircleId)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeUInt64Size(CircleId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CircleJoinReqResponse? other)
    {
        if (other == null) return;
        if (other.HasCircleId) CircleId = other.CircleId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 8u) CircleId = input.ReadUInt64();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
