// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleJoinRequest;

public sealed partial class GetCircleJoinRequestListResponse : IMessage<global::App.Protobuf.CircleJoinRequest.GetCircleJoinRequestListResponse>
{
    private static readonly MessageParser<global::App.Protobuf.CircleJoinRequest.GetCircleJoinRequestListResponse> _parser = new(() => new global::App.Protobuf.CircleJoinRequest.GetCircleJoinRequestListResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.CircleJoinRequest.GetCircleJoinRequestListResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetCircleJoinRequestListResponse() { }

    public GetCircleJoinRequestListResponse(GetCircleJoinRequestListResponse other) : this()
    {
        circleJoinRequests_ = other.circleJoinRequests_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetCircleJoinRequestListResponse Clone() => new(this);

    public const int CircleJoinRequestsFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.CircleJoinRequest> _repeated_circleJoinRequests_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.CircleJoinRequest.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.CircleJoinRequest> circleJoinRequests_ = new();
    public RepeatedField<global::App.Protobuf.Entity.CircleJoinRequest> CircleJoinRequests => circleJoinRequests_;

    public override bool Equals(object? other) => Equals(other as GetCircleJoinRequestListResponse);

    public bool Equals(GetCircleJoinRequestListResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return circleJoinRequests_.Equals(other.circleJoinRequests_) && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= circleJoinRequests_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        circleJoinRequests_.WriteTo(output, _repeated_circleJoinRequests_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = circleJoinRequests_.CalculateSize(_repeated_circleJoinRequests_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetCircleJoinRequestListResponse? other)
    {
        if (other == null) return;
        circleJoinRequests_.Add(other.circleJoinRequests_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) circleJoinRequests_.AddEntriesFrom(input, _repeated_circleJoinRequests_codec);
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
