// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.LiveMusic;

public sealed partial class LiveRankingPlayer : IMessage<global::App.Protobuf.LiveMusic.LiveRankingPlayer>
{
    private static readonly MessageParser<global::App.Protobuf.LiveMusic.LiveRankingPlayer> _parser = new(() => new global::App.Protobuf.LiveMusic.LiveRankingPlayer());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.LiveMusic.LiveRankingPlayer> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public LiveRankingPlayer()
    {
    }

    public LiveRankingPlayer(LiveRankingPlayer other) : this()
    {
        playerData_ = other.playerData_?.Clone();
        score_ = other.score_;
        highScoreDeck_ = other.highScoreDeck_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public LiveRankingPlayer Clone() => new(this);

    public const int PlayerDataFieldNumber = 1;
    private global::App.Protobuf.Entity.PlayerSimpleProfile? playerData_;
    public global::App.Protobuf.Entity.PlayerSimpleProfile? PlayerData
    {
        get => playerData_;
        set => playerData_ = value;
    }

    public const int ScoreFieldNumber = 3;
    private int score_;
    public int Score
    {
        get => score_;
        set => score_ = value;
    }

    public const int HighScoreDeckFieldNumber = 4;
    private global::App.Protobuf.Entity.DeckDetail? highScoreDeck_;
    public global::App.Protobuf.Entity.DeckDetail? HighScoreDeck
    {
        get => highScoreDeck_;
        set => highScoreDeck_ = value;
    }

    public override bool Equals(object? other) => Equals(other as LiveRankingPlayer);

    public bool Equals(LiveRankingPlayer? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(PlayerData, other.PlayerData)) return false;
        if (Score != other.Score) return false;
        if (!Equals(HighScoreDeck, other.HighScoreDeck)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (playerData_ != null) hash ^= playerData_.GetHashCode();
        if (Score != 0) hash ^= Score.GetHashCode();
        if (highScoreDeck_ != null) hash ^= highScoreDeck_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (playerData_ != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(PlayerData);
        }
        if (Score != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(Score);
        }
        if (highScoreDeck_ != null)
        {
            output.WriteRawTag(0x22);
            output.WriteMessage(HighScoreDeck);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (playerData_ != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(PlayerData);
        }
        if (Score != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(Score);
        }
        if (highScoreDeck_ != null)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeMessageSize(HighScoreDeck);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(LiveRankingPlayer? other)
    {
        if (other == null) return;
        if (other.PlayerData != null)
        {
            if (PlayerData == null)
                PlayerData = other.PlayerData.Clone();
            else
                PlayerData.MergeFrom(other.PlayerData);
        }
        if (other.Score != 0) Score = other.Score;
        if (other.HighScoreDeck != null)
        {
            if (HighScoreDeck == null)
                HighScoreDeck = other.HighScoreDeck.Clone();
            else
                HighScoreDeck.MergeFrom(other.HighScoreDeck);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    PlayerData ??= new global::App.Protobuf.Entity.PlayerSimpleProfile();
                    input.ReadMessage(PlayerData);
                    break;
                case 24u:
                    Score = input.ReadInt32();
                    break;
                case 34u:
                    HighScoreDeck ??= new global::App.Protobuf.Entity.DeckDetail();
                    input.ReadMessage(HighScoreDeck);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
