// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.LiveMusic;

public sealed partial class SaveFavoriteRequest : IMessage<global::App.Protobuf.LiveMusic.SaveFavoriteRequest>
{
    private static readonly MessageParser<global::App.Protobuf.LiveMusic.SaveFavoriteRequest> _parser = new(() => new global::App.Protobuf.LiveMusic.SaveFavoriteRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.LiveMusic.SaveFavoriteRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public SaveFavoriteRequest()
    {
    }

    public SaveFavoriteRequest(SaveFavoriteRequest other) : this()
    {
        liveMusicMasterId_ = other.liveMusicMasterId_;
        isFavorite1_ = other.isFavorite1_;
        isFavorite2_ = other.isFavorite2_;
        isFavorite3_ = other.isFavorite3_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public SaveFavoriteRequest Clone() => new(this);

    public const int LiveMusicMasterIdFieldNumber = 1;
    private long liveMusicMasterId_;
    public long LiveMusicMasterId
    {
        get => liveMusicMasterId_;
        set => liveMusicMasterId_ = value;
    }

    public const int IsFavorite1FieldNumber = 2;
    private bool isFavorite1_;
    public bool IsFavorite1
    {
        get => isFavorite1_;
        set => isFavorite1_ = value;
    }

    public const int IsFavorite2FieldNumber = 3;
    private bool isFavorite2_;
    public bool IsFavorite2
    {
        get => isFavorite2_;
        set => isFavorite2_ = value;
    }

    public const int IsFavorite3FieldNumber = 4;
    private bool isFavorite3_;
    public bool IsFavorite3
    {
        get => isFavorite3_;
        set => isFavorite3_ = value;
    }

    public override bool Equals(object? other) => Equals(other as SaveFavoriteRequest);

    public bool Equals(SaveFavoriteRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (LiveMusicMasterId != other.LiveMusicMasterId) return false;
        if (IsFavorite1 != other.IsFavorite1) return false;
        if (IsFavorite2 != other.IsFavorite2) return false;
        if (IsFavorite3 != other.IsFavorite3) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (LiveMusicMasterId != 0L) hash ^= LiveMusicMasterId.GetHashCode();
        if (IsFavorite1) hash ^= IsFavorite1.GetHashCode();
        if (IsFavorite2) hash ^= IsFavorite2.GetHashCode();
        if (IsFavorite3) hash ^= IsFavorite3.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (LiveMusicMasterId != 0L)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(LiveMusicMasterId);
        }
        if (IsFavorite1)
        {
            output.WriteRawTag(0x10);
            output.WriteBool(IsFavorite1);
        }
        if (IsFavorite2)
        {
            output.WriteRawTag(0x18);
            output.WriteBool(IsFavorite2);
        }
        if (IsFavorite3)
        {
            output.WriteRawTag(0x20);
            output.WriteBool(IsFavorite3);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (LiveMusicMasterId != 0L)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(LiveMusicMasterId);
        }
        if (IsFavorite1)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeBoolSize(IsFavorite1);
        }
        if (IsFavorite2)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeBoolSize(IsFavorite2);
        }
        if (IsFavorite3)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeBoolSize(IsFavorite3);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(SaveFavoriteRequest? other)
    {
        if (other == null) return;
        if (other.LiveMusicMasterId != 0L) LiveMusicMasterId = other.LiveMusicMasterId;
        if (other.IsFavorite1) IsFavorite1 = other.IsFavorite1;
        if (other.IsFavorite2) IsFavorite2 = other.IsFavorite2;
        if (other.IsFavorite3) IsFavorite3 = other.IsFavorite3;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    LiveMusicMasterId = input.ReadInt64();
                    break;
                case 16u:
                    IsFavorite1 = input.ReadBool();
                    break;
                case 24u:
                    IsFavorite2 = input.ReadBool();
                    break;
                case 32u:
                    IsFavorite3 = input.ReadBool();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
