// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CarouselHelp;

public sealed partial class ShownRequest : IMessage<global::App.Protobuf.CarouselHelp.ShownRequest>
{
    private static readonly MessageParser<global::App.Protobuf.CarouselHelp.ShownRequest> _parser = new(() => new global::App.Protobuf.CarouselHelp.ShownRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.CarouselHelp.ShownRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public ShownRequest()
    {
    }

    public ShownRequest(ShownRequest other) : this()
    {
        masterIds_ = other.masterIds_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public ShownRequest Clone() => new(this);

    public const int MasterIdsFieldNumber = 1;
    private static readonly FieldCodec<long> _repeated_masterIds_codec = FieldCodec.ForInt64(10u);
    private readonly RepeatedField<long> masterIds_ = new();
    public RepeatedField<long> MasterIds => masterIds_;

    public override bool Equals(object? other) => Equals(other as ShownRequest);

    public bool Equals(ShownRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!masterIds_.Equals(other.masterIds_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= masterIds_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        masterIds_.WriteTo(output, _repeated_masterIds_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = masterIds_.CalculateSize(_repeated_masterIds_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(ShownRequest? other)
    {
        if (other == null) return;
        masterIds_.Add(other.masterIds_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                case 10u:
                    masterIds_.AddEntriesFrom(input, _repeated_masterIds_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
