// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Event;

public sealed partial class GetRankResponse : IMessage<global::App.Protobuf.Event.GetRankResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Event.GetRankResponse> _parser = new(() => new global::App.Protobuf.Event.GetRankResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Event.GetRankResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetRankResponse() { }

    public GetRankResponse(GetRankResponse other) : this()
    {
        rank_ = other.rank_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetRankResponse Clone() => new(this);

    public const int RankFieldNumber = 1;
    private int rank_;
    public int Rank
    {
        get => rank_;
        set => rank_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GetRankResponse);

    public bool Equals(GetRankResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return Rank == other.Rank && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Rank != 0) hash ^= Rank.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Rank != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Rank);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Rank != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Rank);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetRankResponse? other)
    {
        if (other == null) return;
        if (other.Rank != 0) Rank = other.Rank;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 8u) Rank = input.ReadInt32();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
