// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Event;

public sealed partial class GetRankRequest : IMessage<global::App.Protobuf.Event.GetRankRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Event.GetRankRequest> _parser = new(() => new global::App.Protobuf.Event.GetRankRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Event.GetRankRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetRankRequest() { }

    public GetRankRequest(GetRankRequest other) : this()
    {
        eventId_ = other.eventId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetRankRequest Clone() => new(this);

    public const int EventIdFieldNumber = 1;
    private long eventId_;
    public long EventId
    {
        get => eventId_;
        set => eventId_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GetRankRequest);

    public bool Equals(GetRankRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return EventId == other.EventId && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (EventId != 0L) hash ^= EventId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (EventId != 0L)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(EventId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (EventId != 0L)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(EventId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetRankRequest? other)
    {
        if (other == null) return;
        if (other.EventId != 0L) EventId = other.EventId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 8u) EventId = input.ReadInt64();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
