// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Home;

public sealed partial class GetHomeResponse : IMessage<global::App.Protobuf.Home.GetHomeResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Home.GetHomeResponse> _parser = new(() => new global::App.Protobuf.Home.GetHomeResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Home.GetHomeResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetHomeResponse()
    {
    }

    public GetHomeResponse(GetHomeResponse other) : this()
    {
        announcements_ = other.announcements_.Clone();
        loginBonusUpdate_ = other.loginBonusUpdate_.Clone();
        notification_ = other.notification_?.Clone();
        friends_ = other.friends_?.Clone();
        invitations_ = other.invitations_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetHomeResponse Clone() => new(this);

    public const int AnnouncementsFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.Announcement> _repeated_announcements_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.Announcement.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.Announcement> announcements_ = new();
    public RepeatedField<global::App.Protobuf.Entity.Announcement> Announcements => announcements_;

    public const int LoginBonusUpdateFieldNumber = 2;
    private static readonly FieldCodec<global::App.Protobuf.Entity.LoginBonusSheet> _repeated_loginBonusUpdate_codec = FieldCodec.ForMessage(18u, global::App.Protobuf.Entity.LoginBonusSheet.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.LoginBonusSheet> loginBonusUpdate_ = new();
    public RepeatedField<global::App.Protobuf.Entity.LoginBonusSheet> LoginBonusUpdate => loginBonusUpdate_;

    public const int NotificationFieldNumber = 3;
    private global::App.Protobuf.Entity.Notification? notification_;
    public global::App.Protobuf.Entity.Notification? Notification
    {
        get => notification_;
        set => notification_ = value;
    }

    public const int FriendsFieldNumber = 4;
    private global::App.Protobuf.Entity.Friends? friends_;
    public global::App.Protobuf.Entity.Friends? Friends
    {
        get => friends_;
        set => friends_ = value;
    }

    public const int InvitationsFieldNumber = 5;
    private static readonly FieldCodec<global::App.Protobuf.Entity.InvitationProfile> _repeated_invitations_codec = FieldCodec.ForMessage(42u, global::App.Protobuf.Entity.InvitationProfile.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.InvitationProfile> invitations_ = new();
    public RepeatedField<global::App.Protobuf.Entity.InvitationProfile> Invitations => invitations_;

    public override bool Equals(object? other) => Equals(other as GetHomeResponse);

    public bool Equals(GetHomeResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!announcements_.Equals(other.announcements_)) return false;
        if (!loginBonusUpdate_.Equals(other.loginBonusUpdate_)) return false;
        if (!Equals(Notification, other.Notification)) return false;
        if (!Equals(Friends, other.Friends)) return false;
        if (!invitations_.Equals(other.invitations_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= announcements_.GetHashCode();
        hash ^= loginBonusUpdate_.GetHashCode();
        if (Notification != null) hash ^= Notification.GetHashCode();
        if (Friends != null) hash ^= Friends.GetHashCode();
        hash ^= invitations_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        announcements_.WriteTo(output, _repeated_announcements_codec);
        loginBonusUpdate_.WriteTo(output, _repeated_loginBonusUpdate_codec);
        if (Notification != null)
        {
            output.WriteRawTag(0x1A);
            output.WriteMessage(Notification);
        }
        if (Friends != null)
        {
            output.WriteRawTag(0x22);
            output.WriteMessage(Friends);
        }
        invitations_.WriteTo(output, _repeated_invitations_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += announcements_.CalculateSize(_repeated_announcements_codec);
        size += loginBonusUpdate_.CalculateSize(_repeated_loginBonusUpdate_codec);
        if (Notification != null)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeMessageSize(Notification);
        }
        if (Friends != null)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeMessageSize(Friends);
        }
        size += invitations_.CalculateSize(_repeated_invitations_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetHomeResponse? other)
    {
        if (other == null) return;
        announcements_.Add(other.announcements_);
        loginBonusUpdate_.Add(other.loginBonusUpdate_);
        if (other.Notification != null)
        {
            if (Notification == null)
                Notification = other.Notification.Clone();
            else
                Notification.MergeFrom(other.Notification);
        }
        if (other.Friends != null)
        {
            if (Friends == null)
                Friends = other.Friends.Clone();
            else
                Friends.MergeFrom(other.Friends);
        }
        invitations_.Add(other.invitations_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    announcements_.AddEntriesFrom(input, _repeated_announcements_codec);
                    break;
                case 18u:
                    loginBonusUpdate_.AddEntriesFrom(input, _repeated_loginBonusUpdate_codec);
                    break;
                case 26u:
                    Notification ??= new global::App.Protobuf.Entity.Notification();
                    input.ReadMessage(Notification);
                    break;
                case 34u:
                    Friends ??= new global::App.Protobuf.Entity.Friends();
                    input.ReadMessage(Friends);
                    break;
                case 42u:
                    invitations_.AddEntriesFrom(input, _repeated_invitations_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
