// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class Announcement : IMessage<global::App.Protobuf.Entity.Announcement>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.Announcement> _parser = new(() => new global::App.Protobuf.Entity.Announcement());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.Announcement> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public Announcement()
    {
    }

    public Announcement(Announcement other) : this()
    {
        id_ = other.id_;
        category_ = other.category_;
        title_ = other.title_;
        bannerPath_ = other.bannerPath_;
        bannerUrl_ = other.bannerUrl_;
        body_ = other.body_;
        startAt_ = other.startAt_;
        endAt_ = other.endAt_;
        sortOrder_ = other.sortOrder_;
        pickupBannerPath_ = other.pickupBannerPath_;
        pickupBannerUrl_ = other.pickupBannerUrl_;
        pickupStartAt_ = other.pickupStartAt_;
        pickupEndAt_ = other.pickupEndAt_;
        lastUpdatedAt_ = other.lastUpdatedAt_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public Announcement Clone() => new(this);

    public const int IdFieldNumber = 1;
    private long id_ = 0;
    public long Id
    {
        get => id_;
        set => id_ = value;
    }

    public const int CategoryFieldNumber = 2;
    private AnnouncementCategory category_ = 0;
    public AnnouncementCategory Category
    {
        get => category_;
        set => category_ = value;
    }

    public const int TitleFieldNumber = 3;
    private string title_ = "";
    public string Title
    {
        get => title_;
        set => title_ = value ?? "";
    }

    public const int BannerPathFieldNumber = 4;
    private string bannerPath_ = "";
    public string BannerPath
    {
        get => bannerPath_;
        set => bannerPath_ = value ?? "";
    }

    public const int BannerUrlFieldNumber = 5;
    private string bannerUrl_ = "";
    public string BannerUrl
    {
        get => bannerUrl_;
        set => bannerUrl_ = value ?? "";
    }

    public const int BodyFieldNumber = 6;
    private string body_ = "";
    public string Body
    {
        get => body_;
        set => body_ = value ?? "";
    }

    public const int StartAtFieldNumber = 7;
    private long startAt_ = 0;
    public long StartAt
    {
        get => startAt_;
        set => startAt_ = value;
    }

    public const int EndAtFieldNumber = 8;
    private long endAt_ = 0;
    public long EndAt
    {
        get => endAt_;
        set => endAt_ = value;
    }

    public const int SortOrderFieldNumber = 9;
    private int sortOrder_ = 0;
    public int SortOrder
    {
        get => sortOrder_;
        set => sortOrder_ = value;
    }

    public const int PickupBannerPathFieldNumber = 10;
    private string pickupBannerPath_ = "";
    public string PickupBannerPath
    {
        get => pickupBannerPath_;
        set => pickupBannerPath_ = value ?? "";
    }

    public const int PickupBannerUrlFieldNumber = 11;
    private string pickupBannerUrl_ = "";
    public string PickupBannerUrl
    {
        get => pickupBannerUrl_;
        set => pickupBannerUrl_ = value ?? "";
    }

    public const int PickupStartAtFieldNumber = 12;
    private long pickupStartAt_ = 0;
    public long PickupStartAt
    {
        get => pickupStartAt_;
        set => pickupStartAt_ = value;
    }

    public const int PickupEndAtFieldNumber = 13;
    private long pickupEndAt_ = 0;
    public long PickupEndAt
    {
        get => pickupEndAt_;
        set => pickupEndAt_ = value;
    }

    public const int LastUpdatedAtFieldNumber = 14;
    private long lastUpdatedAt_ = 0;
    public long LastUpdatedAt
    {
        get => lastUpdatedAt_;
        set => lastUpdatedAt_ = value;
    }

    public override bool Equals(object? other) => Equals(other as Announcement);

    public bool Equals(Announcement? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Id, other.Id)) return false;
        if (!Equals(Category, other.Category)) return false;
        if (!Equals(Title, other.Title)) return false;
        if (!Equals(BannerPath, other.BannerPath)) return false;
        if (!Equals(BannerUrl, other.BannerUrl)) return false;
        if (!Equals(Body, other.Body)) return false;
        if (!Equals(StartAt, other.StartAt)) return false;
        if (!Equals(EndAt, other.EndAt)) return false;
        if (!Equals(SortOrder, other.SortOrder)) return false;
        if (!Equals(PickupBannerPath, other.PickupBannerPath)) return false;
        if (!Equals(PickupBannerUrl, other.PickupBannerUrl)) return false;
        if (!Equals(PickupStartAt, other.PickupStartAt)) return false;
        if (!Equals(PickupEndAt, other.PickupEndAt)) return false;
        if (!Equals(LastUpdatedAt, other.LastUpdatedAt)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Id != 0) hash ^= Id.GetHashCode();
        if (Category != 0) hash ^= Category.GetHashCode();
        if (Title.Length != 0) hash ^= Title.GetHashCode();
        if (BannerPath.Length != 0) hash ^= BannerPath.GetHashCode();
        if (BannerUrl.Length != 0) hash ^= BannerUrl.GetHashCode();
        if (Body.Length != 0) hash ^= Body.GetHashCode();
        if (StartAt != 0) hash ^= StartAt.GetHashCode();
        if (EndAt != 0) hash ^= EndAt.GetHashCode();
        if (SortOrder != 0) hash ^= SortOrder.GetHashCode();
        if (PickupBannerPath.Length != 0) hash ^= PickupBannerPath.GetHashCode();
        if (PickupBannerUrl.Length != 0) hash ^= PickupBannerUrl.GetHashCode();
        if (PickupStartAt != 0) hash ^= PickupStartAt.GetHashCode();
        if (PickupEndAt != 0) hash ^= PickupEndAt.GetHashCode();
        if (LastUpdatedAt != 0) hash ^= LastUpdatedAt.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Id != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(Id);
        }
        if (Category != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteEnum((int)Category);
        }
        if (Title.Length != 0)
        {
            output.WriteRawTag(0x1A);
            output.WriteString(Title);
        }
        if (BannerPath.Length != 0)
        {
            output.WriteRawTag(0x22);
            output.WriteString(BannerPath);
        }
        if (BannerUrl.Length != 0)
        {
            output.WriteRawTag(0x2A);
            output.WriteString(BannerUrl);
        }
        if (Body.Length != 0)
        {
            output.WriteRawTag(0x32);
            output.WriteString(Body);
        }
        if (StartAt != 0)
        {
            output.WriteRawTag(0x38);
            output.WriteInt64(StartAt);
        }
        if (EndAt != 0)
        {
            output.WriteRawTag(0x40);
            output.WriteInt64(EndAt);
        }
        if (SortOrder != 0)
        {
            output.WriteRawTag(0x48);
            output.WriteInt32(SortOrder);
        }
        if (PickupBannerPath.Length != 0)
        {
            output.WriteRawTag(0x52);
            output.WriteString(PickupBannerPath);
        }
        if (PickupBannerUrl.Length != 0)
        {
            output.WriteRawTag(0x5A);
            output.WriteString(PickupBannerUrl);
        }
        if (PickupStartAt != 0)
        {
            output.WriteRawTag(0x60);
            output.WriteInt64(PickupStartAt);
        }
        if (PickupEndAt != 0)
        {
            output.WriteRawTag(0x68);
            output.WriteInt64(PickupEndAt);
        }
        if (LastUpdatedAt != 0)
        {
            output.WriteRawTag(0x70);
            output.WriteInt64(LastUpdatedAt);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Id != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(Id);
        }
        if (Category != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeEnumSize((int)Category);
        }
        if (Title.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeStringSize(Title);
        }
        if (BannerPath.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeStringSize(BannerPath);
        }
        if (BannerUrl.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeStringSize(BannerUrl);
        }
        if (Body.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeStringSize(Body);
        }
        if (StartAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(7);
            size += CodedOutputStream.ComputeInt64Size(StartAt);
        }
        if (EndAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(8);
            size += CodedOutputStream.ComputeInt64Size(EndAt);
        }
        if (SortOrder != 0)
        {
            size += CodedOutputStream.ComputeTagSize(9);
            size += CodedOutputStream.ComputeInt32Size(SortOrder);
        }
        if (PickupBannerPath.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(10);
            size += CodedOutputStream.ComputeStringSize(PickupBannerPath);
        }
        if (PickupBannerUrl.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(11);
            size += CodedOutputStream.ComputeStringSize(PickupBannerUrl);
        }
        if (PickupStartAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(12);
            size += CodedOutputStream.ComputeInt64Size(PickupStartAt);
        }
        if (PickupEndAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(13);
            size += CodedOutputStream.ComputeInt64Size(PickupEndAt);
        }
        if (LastUpdatedAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(14);
            size += CodedOutputStream.ComputeInt64Size(LastUpdatedAt);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(Announcement? other)
    {
        if (other == null) return;
        if (other.Id != 0) Id = other.Id;
        if (other.Category != 0) Category = other.Category;
        if (other.Title.Length != 0) Title = other.Title;
        if (other.BannerPath.Length != 0) BannerPath = other.BannerPath;
        if (other.BannerUrl.Length != 0) BannerUrl = other.BannerUrl;
        if (other.Body.Length != 0) Body = other.Body;
        if (other.StartAt != 0) StartAt = other.StartAt;
        if (other.EndAt != 0) EndAt = other.EndAt;
        if (other.SortOrder != 0) SortOrder = other.SortOrder;
        if (other.PickupBannerPath.Length != 0) PickupBannerPath = other.PickupBannerPath;
        if (other.PickupBannerUrl.Length != 0) PickupBannerUrl = other.PickupBannerUrl;
        if (other.PickupStartAt != 0) PickupStartAt = other.PickupStartAt;
        if (other.PickupEndAt != 0) PickupEndAt = other.PickupEndAt;
        if (other.LastUpdatedAt != 0) LastUpdatedAt = other.LastUpdatedAt;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Id = input.ReadInt64();
                    break;
                case 16u:
                    Category = (AnnouncementCategory)input.ReadEnum();
                    break;
                case 26u:
                    Title = input.ReadString();
                    break;
                case 34u:
                    BannerPath = input.ReadString();
                    break;
                case 42u:
                    BannerUrl = input.ReadString();
                    break;
                case 50u:
                    Body = input.ReadString();
                    break;
                case 56u:
                    StartAt = input.ReadInt64();
                    break;
                case 64u:
                    EndAt = input.ReadInt64();
                    break;
                case 72u:
                    SortOrder = input.ReadInt32();
                    break;
                case 82u:
                    PickupBannerPath = input.ReadString();
                    break;
                case 90u:
                    PickupBannerUrl = input.ReadString();
                    break;
                case 96u:
                    PickupStartAt = input.ReadInt64();
                    break;
                case 104u:
                    PickupEndAt = input.ReadInt64();
                    break;
                case 112u:
                    LastUpdatedAt = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
