// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class CharacterRank : IMessage<global::App.Protobuf.Entity.CharacterRank>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.CharacterRank> _parser = new(() => new global::App.Protobuf.Entity.CharacterRank());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.CharacterRank> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CharacterRank()
    {
    }

    public CharacterRank(CharacterRank other) : this()
    {
        characterId_ = other.characterId_;
        exp_ = other.exp_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CharacterRank Clone() => new(this);

    public const int CharacterIdFieldNumber = 1;
    private long characterId_ = 0;
    public long CharacterId
    {
        get => characterId_;
        set => characterId_ = value;
    }

    public const int ExpFieldNumber = 2;
    private int exp_ = 0;
    public int Exp
    {
        get => exp_;
        set => exp_ = value;
    }

    public override bool Equals(object? other) => Equals(other as CharacterRank);

    public bool Equals(CharacterRank? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(CharacterId, other.CharacterId)) return false;
        if (!Equals(Exp, other.Exp)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (CharacterId != 0) hash ^= CharacterId.GetHashCode();
        if (Exp != 0) hash ^= Exp.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (CharacterId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(CharacterId);
        }
        if (Exp != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Exp);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (CharacterId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(CharacterId);
        }
        if (Exp != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Exp);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CharacterRank? other)
    {
        if (other == null) return;
        if (other.CharacterId != 0) CharacterId = other.CharacterId;
        if (other.Exp != 0) Exp = other.Exp;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    CharacterId = input.ReadInt64();
                    break;
                case 16u:
                    Exp = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
