// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class CharacterFriendshipRankReward : IMessage<global::App.Protobuf.Entity.CharacterFriendshipRankReward>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.CharacterFriendshipRankReward> _parser = new(() => new global::App.Protobuf.Entity.CharacterFriendshipRankReward());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.CharacterFriendshipRankReward> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CharacterFriendshipRankReward()
    {
    }

    public CharacterFriendshipRankReward(CharacterFriendshipRankReward other) : this()
    {
        friendshipId_ = other.friendshipId_;
        rewardId_ = other.rewardId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CharacterFriendshipRankReward Clone() => new(this);

    public const int FriendshipIdFieldNumber = 1;
    private long friendshipId_ = 0;
    public long FriendshipId
    {
        get => friendshipId_;
        set => friendshipId_ = value;
    }

    public const int RewardIdFieldNumber = 2;
    private long rewardId_ = 0;
    public long RewardId
    {
        get => rewardId_;
        set => rewardId_ = value;
    }

    public override bool Equals(object? other) => Equals(other as CharacterFriendshipRankReward);

    public bool Equals(CharacterFriendshipRankReward? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(FriendshipId, other.FriendshipId)) return false;
        if (!Equals(RewardId, other.RewardId)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (FriendshipId != 0) hash ^= FriendshipId.GetHashCode();
        if (RewardId != 0) hash ^= RewardId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (FriendshipId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(FriendshipId);
        }
        if (RewardId != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(RewardId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (FriendshipId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(FriendshipId);
        }
        if (RewardId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(RewardId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CharacterFriendshipRankReward? other)
    {
        if (other == null) return;
        if (other.FriendshipId != 0) FriendshipId = other.FriendshipId;
        if (other.RewardId != 0) RewardId = other.RewardId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    FriendshipId = input.ReadInt64();
                    break;
                case 16u:
                    RewardId = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
