// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class CharacterMissionReceived : IMessage<global::App.Protobuf.Entity.CharacterMissionReceived>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.CharacterMissionReceived> _parser = new(() => new global::App.Protobuf.Entity.CharacterMissionReceived());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.CharacterMissionReceived> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CharacterMissionReceived()
    {
    }

    public CharacterMissionReceived(CharacterMissionReceived other) : this()
    {
        characterId_ = other.characterId_;
        missionIds_ = other.missionIds_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CharacterMissionReceived Clone() => new(this);

    public const int CharacterIdFieldNumber = 1;
    private long characterId_ = 0;
    public long CharacterId
    {
        get => characterId_;
        set => characterId_ = value;
    }

    public const int MissionIdsFieldNumber = 2;
    private static readonly FieldCodec<long> _repeated_missionIds_codec = FieldCodec.ForInt64(18u);
    private readonly RepeatedField<long> missionIds_ = new();
    public RepeatedField<long> MissionIds => missionIds_;

    public override bool Equals(object? other) => Equals(other as CharacterMissionReceived);

    public bool Equals(CharacterMissionReceived? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(CharacterId, other.CharacterId)) return false;
        if (!missionIds_.Equals(other.missionIds_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (CharacterId != 0) hash ^= CharacterId.GetHashCode();
        hash ^= missionIds_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (CharacterId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(CharacterId);
        }
        missionIds_.WriteTo(output, _repeated_missionIds_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (CharacterId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(CharacterId);
        }
        size += missionIds_.CalculateSize(_repeated_missionIds_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CharacterMissionReceived? other)
    {
        if (other == null) return;
        if (other.CharacterId != 0) CharacterId = other.CharacterId;
        missionIds_.Add(other.missionIds_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    CharacterId = input.ReadInt64();
                    break;
                case 16u:
                case 18u:
                    missionIds_.AddEntriesFrom(input, _repeated_missionIds_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
