// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class CircleWithMasterPlayer : IMessage<global::App.Protobuf.Entity.CircleWithMasterPlayer>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.CircleWithMasterPlayer> _parser = new(() => new global::App.Protobuf.Entity.CircleWithMasterPlayer());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.CircleWithMasterPlayer> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CircleWithMasterPlayer()
    {
    }

    public CircleWithMasterPlayer(CircleWithMasterPlayer other) : this()
    {
        circle_ = other.circle_?.Clone();
        profile_ = other.profile_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CircleWithMasterPlayer Clone() => new(this);

    public const int CircleFieldNumber = 1;
    private Circle? circle_;
    public Circle? Circle
    {
        get => circle_;
        set => circle_ = value;
    }

    public const int ProfileFieldNumber = 4;
    private PlayerSimpleProfile? profile_;
    public PlayerSimpleProfile? Profile
    {
        get => profile_;
        set => profile_ = value;
    }

    public override bool Equals(object? other) => Equals(other as CircleWithMasterPlayer);

    public bool Equals(CircleWithMasterPlayer? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Circle, other.Circle)) return false;
        if (!Equals(Profile, other.Profile)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Circle != null) hash ^= Circle.GetHashCode();
        if (Profile != null) hash ^= Profile.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Circle != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(Circle);
        }
        if (Profile != null)
        {
            output.WriteRawTag(0x22);
            output.WriteMessage(Profile);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Circle != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(Circle);
        }
        if (Profile != null)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeMessageSize(Profile);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CircleWithMasterPlayer? other)
    {
        if (other == null) return;
        if (other.Circle != null)
        {
            if (Circle == null)
                Circle = other.Circle.Clone();
            else
                Circle.MergeFrom(other.Circle);
        }
        if (other.Profile != null)
        {
            if (Profile == null)
                Profile = other.Profile.Clone();
            else
                Profile.MergeFrom(other.Profile);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Circle ??= new global::App.Protobuf.Entity.Circle();
                    input.ReadMessage(Circle);
                    break;
                case 34u:
                    Profile ??= new global::App.Protobuf.Entity.PlayerSimpleProfile();
                    input.ReadMessage(Profile);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
