// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class CircleMissionProgress : IMessage<global::App.Protobuf.Entity.CircleMissionProgress>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.CircleMissionProgress> _parser = new(() => new global::App.Protobuf.Entity.CircleMissionProgress());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.CircleMissionProgress> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CircleMissionProgress()
    {
    }

    public CircleMissionProgress(CircleMissionProgress other) : this()
    {
        missionId_ = other.missionId_;
        progress_ = other.progress_;
        isCompleted_ = other.isCompleted_;
        isReceived_ = other.isReceived_;
        startAt_ = other.startAt_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CircleMissionProgress Clone() => new(this);

    public const int MissionIdFieldNumber = 1;
    private long missionId_ = 0;
    public long MissionId
    {
        get => missionId_;
        set => missionId_ = value;
    }

    public const int ProgressFieldNumber = 2;
    private long progress_ = 0;
    public long Progress
    {
        get => progress_;
        set => progress_ = value;
    }

    public const int IsCompletedFieldNumber = 3;
    private bool isCompleted_ = false;
    public bool IsCompleted
    {
        get => isCompleted_;
        set => isCompleted_ = value;
    }

    public const int IsReceivedFieldNumber = 4;
    private bool isReceived_ = false;
    public bool IsReceived
    {
        get => isReceived_;
        set => isReceived_ = value;
    }

    public const int StartAtFieldNumber = 5;
    private long startAt_ = 0;
    public long StartAt
    {
        get => startAt_;
        set => startAt_ = value;
    }

    public override bool Equals(object? other) => Equals(other as CircleMissionProgress);

    public bool Equals(CircleMissionProgress? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(MissionId, other.MissionId)) return false;
        if (!Equals(Progress, other.Progress)) return false;
        if (!Equals(IsCompleted, other.IsCompleted)) return false;
        if (!Equals(IsReceived, other.IsReceived)) return false;
        if (!Equals(StartAt, other.StartAt)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (MissionId != 0) hash ^= MissionId.GetHashCode();
        if (Progress != 0) hash ^= Progress.GetHashCode();
        if (IsCompleted) hash ^= IsCompleted.GetHashCode();
        if (IsReceived) hash ^= IsReceived.GetHashCode();
        if (StartAt != 0) hash ^= StartAt.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (MissionId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(MissionId);
        }
        if (Progress != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(Progress);
        }
        if (IsCompleted)
        {
            output.WriteRawTag(0x18);
            output.WriteBool(IsCompleted);
        }
        if (IsReceived)
        {
            output.WriteRawTag(0x20);
            output.WriteBool(IsReceived);
        }
        if (StartAt != 0)
        {
            output.WriteRawTag(0x28);
            output.WriteInt64(StartAt);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (MissionId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(MissionId);
        }
        if (Progress != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(Progress);
        }
        if (IsCompleted)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeBoolSize(IsCompleted);
        }
        if (IsReceived)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeBoolSize(IsReceived);
        }
        if (StartAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeInt64Size(StartAt);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CircleMissionProgress? other)
    {
        if (other == null) return;
        if (other.MissionId != 0) MissionId = other.MissionId;
        if (other.Progress != 0) Progress = other.Progress;
        if (other.IsCompleted) IsCompleted = other.IsCompleted;
        if (other.IsReceived) IsReceived = other.IsReceived;
        if (other.StartAt != 0) StartAt = other.StartAt;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    MissionId = input.ReadInt64();
                    break;
                case 16u:
                    Progress = input.ReadInt64();
                    break;
                case 24u:
                    IsCompleted = input.ReadBool();
                    break;
                case 32u:
                    IsReceived = input.ReadBool();
                    break;
                case 40u:
                    StartAt = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
