// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class CircleInvitation : IMessage<global::App.Protobuf.Entity.CircleInvitation>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.CircleInvitation> _parser = new(() => new global::App.Protobuf.Entity.CircleInvitation());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.CircleInvitation> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CircleInvitation()
    {
    }

    public CircleInvitation(CircleInvitation other) : this()
    {
        circleId_ = other.circleId_;
        playerId_ = other.playerId_;
        circleDetail_ = other.circleDetail_?.Clone();
        profile_ = other.profile_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CircleInvitation Clone() => new(this);

    public const int CircleIdFieldNumber = 1;
    private ulong circleId_ = 0;
    public ulong CircleId
    {
        get => circleId_;
        set => circleId_ = value;
    }

    public const int PlayerIdFieldNumber = 2;
    private string playerId_ = "";
    public string PlayerId
    {
        get => playerId_;
        set => playerId_ = value ?? "";
    }

    public const int CircleDetailFieldNumber = 3;
    private Circle? circleDetail_;
    public Circle? CircleDetail
    {
        get => circleDetail_;
        set => circleDetail_ = value;
    }

    public const int ProfileFieldNumber = 4;
    private PlayerSimpleProfile? profile_;
    public PlayerSimpleProfile? Profile
    {
        get => profile_;
        set => profile_ = value;
    }

    public override bool Equals(object? other) => Equals(other as CircleInvitation);

    public bool Equals(CircleInvitation? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(CircleId, other.CircleId)) return false;
        if (!Equals(PlayerId, other.PlayerId)) return false;
        if (!Equals(CircleDetail, other.CircleDetail)) return false;
        if (!Equals(Profile, other.Profile)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (CircleId != 0) hash ^= CircleId.GetHashCode();
        if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
        if (CircleDetail != null) hash ^= CircleDetail.GetHashCode();
        if (Profile != null) hash ^= Profile.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (CircleId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteUInt64(CircleId);
        }
        if (PlayerId.Length != 0)
        {
            output.WriteRawTag(0x12);
            output.WriteString(PlayerId);
        }
        if (CircleDetail != null)
        {
            output.WriteRawTag(0x1A);
            output.WriteMessage(CircleDetail);
        }
        if (Profile != null)
        {
            output.WriteRawTag(0x22);
            output.WriteMessage(Profile);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (CircleId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeUInt64Size(CircleId);
        }
        if (PlayerId.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeStringSize(PlayerId);
        }
        if (CircleDetail != null)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeMessageSize(CircleDetail);
        }
        if (Profile != null)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeMessageSize(Profile);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CircleInvitation? other)
    {
        if (other == null) return;
        if (other.CircleId != 0) CircleId = other.CircleId;
        if (other.PlayerId.Length != 0) PlayerId = other.PlayerId;
        if (other.CircleDetail != null)
        {
            if (CircleDetail == null)
                CircleDetail = other.CircleDetail.Clone();
            else
                CircleDetail.MergeFrom(other.CircleDetail);
        }
        if (other.Profile != null)
        {
            if (Profile == null)
                Profile = other.Profile.Clone();
            else
                Profile.MergeFrom(other.Profile);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    CircleId = input.ReadUInt64();
                    break;
                case 18u:
                    PlayerId = input.ReadString();
                    break;
                case 26u:
                    CircleDetail ??= new global::App.Protobuf.Entity.Circle();
                    input.ReadMessage(CircleDetail);
                    break;
                case 34u:
                    Profile ??= new global::App.Protobuf.Entity.PlayerSimpleProfile();
                    input.ReadMessage(Profile);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
