// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class CircleRankUpRewardReceived : IMessage<global::App.Protobuf.Entity.CircleRankUpRewardReceived>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.CircleRankUpRewardReceived> _parser = new(() => new global::App.Protobuf.Entity.CircleRankUpRewardReceived());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.CircleRankUpRewardReceived> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public CircleRankUpRewardReceived()
    {
    }

    public CircleRankUpRewardReceived(CircleRankUpRewardReceived other) : this()
    {
        playerId_ = other.playerId_;
        circleId_ = other.circleId_;
        circleRank_ = other.circleRank_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public CircleRankUpRewardReceived Clone() => new(this);

    public const int PlayerIdFieldNumber = 1;
    private string playerId_ = "";
    public string PlayerId
    {
        get => playerId_;
        set => playerId_ = value ?? "";
    }

    public const int CircleIdFieldNumber = 2;
    private ulong circleId_ = 0;
    public ulong CircleId
    {
        get => circleId_;
        set => circleId_ = value;
    }

    public const int CircleRankFieldNumber = 3;
    private uint circleRank_ = 0;
    public uint CircleRank
    {
        get => circleRank_;
        set => circleRank_ = value;
    }

    public override bool Equals(object? other) => Equals(other as CircleRankUpRewardReceived);

    public bool Equals(CircleRankUpRewardReceived? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(PlayerId, other.PlayerId)) return false;
        if (!Equals(CircleId, other.CircleId)) return false;
        if (!Equals(CircleRank, other.CircleRank)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
        if (CircleId != 0) hash ^= CircleId.GetHashCode();
        if (CircleRank != 0) hash ^= CircleRank.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (PlayerId.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(PlayerId);
        }
        if (CircleId != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteUInt64(CircleId);
        }
        if (CircleRank != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteUInt32(CircleRank);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (PlayerId.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(PlayerId);
        }
        if (CircleId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeUInt64Size(CircleId);
        }
        if (CircleRank != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeUInt32Size(CircleRank);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(CircleRankUpRewardReceived? other)
    {
        if (other == null) return;
        if (other.PlayerId.Length != 0) PlayerId = other.PlayerId;
        if (other.CircleId != 0) CircleId = other.CircleId;
        if (other.CircleRank != 0) CircleRank = other.CircleRank;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    PlayerId = input.ReadString();
                    break;
                case 16u:
                    CircleId = input.ReadUInt64();
                    break;
                case 24u:
                    CircleRank = input.ReadUInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
