// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class DeckCard : IMessage<global::App.Protobuf.Entity.DeckCard>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.DeckCard> _parser = new(() => new global::App.Protobuf.Entity.DeckCard());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.DeckCard> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public DeckCard()
    {
    }

    public DeckCard(DeckCard other) : this()
    {
        slotIndex_ = other.slotIndex_;
        performanceOrderIndex_ = other.performanceOrderIndex_;
        memberCardId_ = other.memberCardId_;
        supportCardId_ = other.supportCardId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public DeckCard Clone() => new(this);

    public const int SlotIndexFieldNumber = 1;
    private int slotIndex_ = 0;
    public int SlotIndex
    {
        get => slotIndex_;
        set => slotIndex_ = value;
    }

    public const int PerformanceOrderIndexFieldNumber = 2;
    private int performanceOrderIndex_ = 0;
    public int PerformanceOrderIndex
    {
        get => performanceOrderIndex_;
        set => performanceOrderIndex_ = value;
    }

    public const int MemberCardIdFieldNumber = 3;
    private long memberCardId_ = 0;
    public long MemberCardId
    {
        get => memberCardId_;
        set => memberCardId_ = value;
    }

    public const int SupportCardIdFieldNumber = 4;
    private long supportCardId_ = 0;
    public long SupportCardId
    {
        get => supportCardId_;
        set => supportCardId_ = value;
    }

    public override bool Equals(object? other) => Equals(other as DeckCard);

    public bool Equals(DeckCard? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(SlotIndex, other.SlotIndex)) return false;
        if (!Equals(PerformanceOrderIndex, other.PerformanceOrderIndex)) return false;
        if (!Equals(MemberCardId, other.MemberCardId)) return false;
        if (!Equals(SupportCardId, other.SupportCardId)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (SlotIndex != 0) hash ^= SlotIndex.GetHashCode();
        if (PerformanceOrderIndex != 0) hash ^= PerformanceOrderIndex.GetHashCode();
        if (MemberCardId != 0) hash ^= MemberCardId.GetHashCode();
        if (SupportCardId != 0) hash ^= SupportCardId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (SlotIndex != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(SlotIndex);
        }
        if (PerformanceOrderIndex != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(PerformanceOrderIndex);
        }
        if (MemberCardId != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt64(MemberCardId);
        }
        if (SupportCardId != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt64(SupportCardId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (SlotIndex != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(SlotIndex);
        }
        if (PerformanceOrderIndex != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(PerformanceOrderIndex);
        }
        if (MemberCardId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt64Size(MemberCardId);
        }
        if (SupportCardId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt64Size(SupportCardId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(DeckCard? other)
    {
        if (other == null) return;
        if (other.SlotIndex != 0) SlotIndex = other.SlotIndex;
        if (other.PerformanceOrderIndex != 0) PerformanceOrderIndex = other.PerformanceOrderIndex;
        if (other.MemberCardId != 0) MemberCardId = other.MemberCardId;
        if (other.SupportCardId != 0) SupportCardId = other.SupportCardId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    SlotIndex = input.ReadInt32();
                    break;
                case 16u:
                    PerformanceOrderIndex = input.ReadInt32();
                    break;
                case 24u:
                    MemberCardId = input.ReadInt64();
                    break;
                case 32u:
                    SupportCardId = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
