// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class DeckDetail : IMessage<global::App.Protobuf.Entity.DeckDetail>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.DeckDetail> _parser = new(() => new global::App.Protobuf.Entity.DeckDetail());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.DeckDetail> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public DeckDetail()
    {
    }

    public DeckDetail(DeckDetail other) : this()
    {
        id_ = other.id_;
        name_ = other.name_;
        cards_ = other.cards_.Clone();
        totalPower_ = other.totalPower_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public DeckDetail Clone() => new(this);

    public const int IdFieldNumber = 1;
    private int id_ = 0;
    public int Id
    {
        get => id_;
        set => id_ = value;
    }

    public const int NameFieldNumber = 2;
    private string name_ = "";
    public string Name
    {
        get => name_;
        set => name_ = value ?? "";
    }

    public const int CardsFieldNumber = 3;
    private static readonly FieldCodec<global::App.Protobuf.Entity.DeckCardDetail> _repeated_cards_codec = FieldCodec.ForMessage(26u, global::App.Protobuf.Entity.DeckCardDetail.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.DeckCardDetail> cards_ = new();
    public RepeatedField<global::App.Protobuf.Entity.DeckCardDetail> Cards => cards_;

    public const int TotalPowerFieldNumber = 4;
    private int totalPower_ = 0;
    public int TotalPower
    {
        get => totalPower_;
        set => totalPower_ = value;
    }

    public override bool Equals(object? other) => Equals(other as DeckDetail);

    public bool Equals(DeckDetail? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Id, other.Id)) return false;
        if (!Equals(Name, other.Name)) return false;
        if (!cards_.Equals(other.cards_)) return false;
        if (!Equals(TotalPower, other.TotalPower)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Id != 0) hash ^= Id.GetHashCode();
        if (Name.Length != 0) hash ^= Name.GetHashCode();
        hash ^= cards_.GetHashCode();
        if (TotalPower != 0) hash ^= TotalPower.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Id != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Id);
        }
        if (Name.Length != 0)
        {
            output.WriteRawTag(0x12);
            output.WriteString(Name);
        }
        cards_.WriteTo(output, _repeated_cards_codec);
        if (TotalPower != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt32(TotalPower);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Id != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Id);
        }
        if (Name.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeStringSize(Name);
        }
        size += cards_.CalculateSize(_repeated_cards_codec);
        if (TotalPower != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt32Size(TotalPower);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(DeckDetail? other)
    {
        if (other == null) return;
        if (other.Id != 0) Id = other.Id;
        if (other.Name.Length != 0) Name = other.Name;
        cards_.Add(other.cards_);
        if (other.TotalPower != 0) TotalPower = other.TotalPower;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Id = input.ReadInt32();
                    break;
                case 18u:
                    Name = input.ReadString();
                    break;
                case 26u:
                    cards_.AddEntriesFrom(input, _repeated_cards_codec);
                    break;
                case 32u:
                    TotalPower = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
