// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class DeckMemberCardDetail : IMessage<global::App.Protobuf.Entity.DeckMemberCardDetail>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.DeckMemberCardDetail> _parser = new(() => new global::App.Protobuf.Entity.DeckMemberCardDetail());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.DeckMemberCardDetail> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public DeckMemberCardDetail()
    {
    }

    public DeckMemberCardDetail(DeckMemberCardDetail other) : this()
    {
        cardId_ = other.cardId_;
        exp_ = other.exp_;
        awakeCount_ = other.awakeCount_;
        cardRank_ = other.cardRank_;
        liveSkillLevel_ = other.liveSkillLevel_;
        performanceSkillLevel_ = other.performanceSkillLevel_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public DeckMemberCardDetail Clone() => new(this);

    public const int CardIdFieldNumber = 1;
    private long cardId_ = 0;
    public long CardId
    {
        get => cardId_;
        set => cardId_ = value;
    }

    public const int ExpFieldNumber = 2;
    private int exp_ = 0;
    public int Exp
    {
        get => exp_;
        set => exp_ = value;
    }

    public const int AwakeCountFieldNumber = 3;
    private int awakeCount_ = 0;
    public int AwakeCount
    {
        get => awakeCount_;
        set => awakeCount_ = value;
    }

    public const int CardRankFieldNumber = 4;
    private int cardRank_ = 0;
    public int CardRank
    {
        get => cardRank_;
        set => cardRank_ = value;
    }

    public const int LiveSkillLevelFieldNumber = 5;
    private int liveSkillLevel_ = 0;
    public int LiveSkillLevel
    {
        get => liveSkillLevel_;
        set => liveSkillLevel_ = value;
    }

    public const int PerformanceSkillLevelFieldNumber = 6;
    private int performanceSkillLevel_ = 0;
    public int PerformanceSkillLevel
    {
        get => performanceSkillLevel_;
        set => performanceSkillLevel_ = value;
    }

    public override bool Equals(object? other) => Equals(other as DeckMemberCardDetail);

    public bool Equals(DeckMemberCardDetail? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(CardId, other.CardId)) return false;
        if (!Equals(Exp, other.Exp)) return false;
        if (!Equals(AwakeCount, other.AwakeCount)) return false;
        if (!Equals(CardRank, other.CardRank)) return false;
        if (!Equals(LiveSkillLevel, other.LiveSkillLevel)) return false;
        if (!Equals(PerformanceSkillLevel, other.PerformanceSkillLevel)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (CardId != 0) hash ^= CardId.GetHashCode();
        if (Exp != 0) hash ^= Exp.GetHashCode();
        if (AwakeCount != 0) hash ^= AwakeCount.GetHashCode();
        if (CardRank != 0) hash ^= CardRank.GetHashCode();
        if (LiveSkillLevel != 0) hash ^= LiveSkillLevel.GetHashCode();
        if (PerformanceSkillLevel != 0) hash ^= PerformanceSkillLevel.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (CardId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(CardId);
        }
        if (Exp != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Exp);
        }
        if (AwakeCount != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(AwakeCount);
        }
        if (CardRank != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt32(CardRank);
        }
        if (LiveSkillLevel != 0)
        {
            output.WriteRawTag(0x28);
            output.WriteInt32(LiveSkillLevel);
        }
        if (PerformanceSkillLevel != 0)
        {
            output.WriteRawTag(0x30);
            output.WriteInt32(PerformanceSkillLevel);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (CardId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(CardId);
        }
        if (Exp != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Exp);
        }
        if (AwakeCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(AwakeCount);
        }
        if (CardRank != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt32Size(CardRank);
        }
        if (LiveSkillLevel != 0)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeInt32Size(LiveSkillLevel);
        }
        if (PerformanceSkillLevel != 0)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeInt32Size(PerformanceSkillLevel);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(DeckMemberCardDetail? other)
    {
        if (other == null) return;
        if (other.CardId != 0) CardId = other.CardId;
        if (other.Exp != 0) Exp = other.Exp;
        if (other.AwakeCount != 0) AwakeCount = other.AwakeCount;
        if (other.CardRank != 0) CardRank = other.CardRank;
        if (other.LiveSkillLevel != 0) LiveSkillLevel = other.LiveSkillLevel;
        if (other.PerformanceSkillLevel != 0) PerformanceSkillLevel = other.PerformanceSkillLevel;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    CardId = input.ReadInt64();
                    break;
                case 16u:
                    Exp = input.ReadInt32();
                    break;
                case 24u:
                    AwakeCount = input.ReadInt32();
                    break;
                case 32u:
                    CardRank = input.ReadInt32();
                    break;
                case 40u:
                    LiveSkillLevel = input.ReadInt32();
                    break;
                case 48u:
                    PerformanceSkillLevel = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
