// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class EventBoxGachaReward : IMessage<global::App.Protobuf.Entity.EventBoxGachaReward>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.EventBoxGachaReward> _parser = new(() => new global::App.Protobuf.Entity.EventBoxGachaReward());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.EventBoxGachaReward> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public EventBoxGachaReward()
    {
    }

    public EventBoxGachaReward(EventBoxGachaReward other) : this()
    {
        eventId_ = other.eventId_;
        rewardId_ = other.rewardId_;
        count_ = other.count_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public EventBoxGachaReward Clone() => new(this);

    public const int EventIdFieldNumber = 1;
    private long eventId_ = 0;
    public long EventId
    {
        get => eventId_;
        set => eventId_ = value;
    }

    public const int RewardIdFieldNumber = 2;
    private long rewardId_ = 0;
    public long RewardId
    {
        get => rewardId_;
        set => rewardId_ = value;
    }

    public const int CountFieldNumber = 3;
    private int count_ = 0;
    public int Count
    {
        get => count_;
        set => count_ = value;
    }

    public override bool Equals(object? other) => Equals(other as EventBoxGachaReward);

    public bool Equals(EventBoxGachaReward? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(EventId, other.EventId)) return false;
        if (!Equals(RewardId, other.RewardId)) return false;
        if (!Equals(Count, other.Count)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (EventId != 0) hash ^= EventId.GetHashCode();
        if (RewardId != 0) hash ^= RewardId.GetHashCode();
        if (Count != 0) hash ^= Count.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (EventId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(EventId);
        }
        if (RewardId != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(RewardId);
        }
        if (Count != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(Count);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (EventId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(EventId);
        }
        if (RewardId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(RewardId);
        }
        if (Count != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(Count);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(EventBoxGachaReward? other)
    {
        if (other == null) return;
        if (other.EventId != 0) EventId = other.EventId;
        if (other.RewardId != 0) RewardId = other.RewardId;
        if (other.Count != 0) Count = other.Count;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    EventId = input.ReadInt64();
                    break;
                case 16u:
                    RewardId = input.ReadInt64();
                    break;
                case 24u:
                    Count = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
