// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class FriendProfiles : IMessage<global::App.Protobuf.Entity.FriendProfiles>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.FriendProfiles> _parser = new(() => new global::App.Protobuf.Entity.FriendProfiles());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.FriendProfiles> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public FriendProfiles()
    {
    }

    public FriendProfiles(FriendProfiles other) : this()
    {
        playerProfiles_ = other.playerProfiles_.Clone();
        limit_ = other.limit_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public FriendProfiles Clone() => new(this);

    public const int PlayerProfilesFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.PlayerSimpleProfile> _repeated_playerProfiles_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.PlayerSimpleProfile.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.PlayerSimpleProfile> playerProfiles_ = new();
    public RepeatedField<global::App.Protobuf.Entity.PlayerSimpleProfile> PlayerProfiles => playerProfiles_;

    public const int LimitFieldNumber = 2;
    private int limit_ = 0;
    public int Limit
    {
        get => limit_;
        set => limit_ = value;
    }

    public override bool Equals(object? other) => Equals(other as FriendProfiles);

    public bool Equals(FriendProfiles? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!playerProfiles_.Equals(other.playerProfiles_)) return false;
        if (!Equals(Limit, other.Limit)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= playerProfiles_.GetHashCode();
        if (Limit != 0) hash ^= Limit.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        playerProfiles_.WriteTo(output, _repeated_playerProfiles_codec);
        if (Limit != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Limit);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += playerProfiles_.CalculateSize(_repeated_playerProfiles_codec);
        if (Limit != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Limit);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(FriendProfiles? other)
    {
        if (other == null) return;
        playerProfiles_.Add(other.playerProfiles_);
        if (other.Limit != 0) Limit = other.Limit;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    playerProfiles_.AddEntriesFrom(input, _repeated_playerProfiles_codec);
                    break;
                case 16u:
                    Limit = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
