// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class GachaCount : IMessage<global::App.Protobuf.Entity.GachaCount>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.GachaCount> _parser = new(() => new global::App.Protobuf.Entity.GachaCount());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.GachaCount> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GachaCount()
    {
    }

    public GachaCount(GachaCount other) : this()
    {
        productId_ = other.productId_;
        count_ = other.count_;
        lastExecute_ = other.lastExecute_;
        gachaId_ = other.gachaId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GachaCount Clone() => new(this);

    public const int ProductIdFieldNumber = 1;
    private long productId_ = 0;
    public long ProductId
    {
        get => productId_;
        set => productId_ = value;
    }

    public const int CountFieldNumber = 2;
    private int count_ = 0;
    public int Count
    {
        get => count_;
        set => count_ = value;
    }

    public const int LastExecuteFieldNumber = 3;
    private long lastExecute_ = 0;
    public long LastExecute
    {
        get => lastExecute_;
        set => lastExecute_ = value;
    }

    public const int GachaIdFieldNumber = 4;
    private long gachaId_ = 0;
    public long GachaId
    {
        get => gachaId_;
        set => gachaId_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GachaCount);

    public bool Equals(GachaCount? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(ProductId, other.ProductId)) return false;
        if (!Equals(Count, other.Count)) return false;
        if (!Equals(LastExecute, other.LastExecute)) return false;
        if (!Equals(GachaId, other.GachaId)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (ProductId != 0) hash ^= ProductId.GetHashCode();
        if (Count != 0) hash ^= Count.GetHashCode();
        if (LastExecute != 0) hash ^= LastExecute.GetHashCode();
        if (GachaId != 0) hash ^= GachaId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (ProductId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(ProductId);
        }
        if (Count != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Count);
        }
        if (LastExecute != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt64(LastExecute);
        }
        if (GachaId != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt64(GachaId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (ProductId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(ProductId);
        }
        if (Count != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Count);
        }
        if (LastExecute != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt64Size(LastExecute);
        }
        if (GachaId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt64Size(GachaId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GachaCount? other)
    {
        if (other == null) return;
        if (other.ProductId != 0) ProductId = other.ProductId;
        if (other.Count != 0) Count = other.Count;
        if (other.LastExecute != 0) LastExecute = other.LastExecute;
        if (other.GachaId != 0) GachaId = other.GachaId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    ProductId = input.ReadInt64();
                    break;
                case 16u:
                    Count = input.ReadInt32();
                    break;
                case 24u:
                    LastExecute = input.ReadInt64();
                    break;
                case 32u:
                    GachaId = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
