// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class GachaHistory : IMessage<global::App.Protobuf.Entity.GachaHistory>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.GachaHistory> _parser = new(() => new global::App.Protobuf.Entity.GachaHistory());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.GachaHistory> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GachaHistory()
    {
    }

    public GachaHistory(GachaHistory other) : this()
    {
        prizeId_ = other.prizeId_;
        gainAt_ = other.gainAt_;
        converted_ = other.converted_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GachaHistory Clone() => new(this);

    public const int PrizeIdFieldNumber = 1;
    private long prizeId_ = 0;
    public long PrizeId
    {
        get => prizeId_;
        set => prizeId_ = value;
    }

    public const int GainAtFieldNumber = 2;
    private long gainAt_ = 0;
    public long GainAt
    {
        get => gainAt_;
        set => gainAt_ = value;
    }

    public const int ConvertedFieldNumber = 3;
    private bool converted_ = false;
    public bool Converted
    {
        get => converted_;
        set => converted_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GachaHistory);

    public bool Equals(GachaHistory? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(PrizeId, other.PrizeId)) return false;
        if (!Equals(GainAt, other.GainAt)) return false;
        if (!Equals(Converted, other.Converted)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (PrizeId != 0) hash ^= PrizeId.GetHashCode();
        if (GainAt != 0) hash ^= GainAt.GetHashCode();
        if (Converted) hash ^= Converted.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (PrizeId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(PrizeId);
        }
        if (GainAt != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(GainAt);
        }
        if (Converted)
        {
            output.WriteRawTag(0x18);
            output.WriteBool(Converted);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (PrizeId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(PrizeId);
        }
        if (GainAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(GainAt);
        }
        if (Converted)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeBoolSize(Converted);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GachaHistory? other)
    {
        if (other == null) return;
        if (other.PrizeId != 0) PrizeId = other.PrizeId;
        if (other.GainAt != 0) GainAt = other.GainAt;
        if (other.Converted) Converted = other.Converted;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    PrizeId = input.ReadInt64();
                    break;
                case 16u:
                    GainAt = input.ReadInt64();
                    break;
                case 24u:
                    Converted = input.ReadBool();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
