// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class GekisouRankingPlayer : IMessage<global::App.Protobuf.Entity.GekisouRankingPlayer>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.GekisouRankingPlayer> _parser = new(() => new global::App.Protobuf.Entity.GekisouRankingPlayer());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.GekisouRankingPlayer> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GekisouRankingPlayer()
    {
    }

    public GekisouRankingPlayer(GekisouRankingPlayer other) : this()
    {
        playerId_ = other.playerId_;
        rank_ = other.rank_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GekisouRankingPlayer Clone() => new(this);

    public const int PlayerIdFieldNumber = 1;
    private string playerId_ = "";
    public string PlayerId
    {
        get => playerId_;
        set => playerId_ = value ?? "";
    }

    public const int RankFieldNumber = 2;
    private int rank_ = 0;
    public int Rank
    {
        get => rank_;
        set => rank_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GekisouRankingPlayer);

    public bool Equals(GekisouRankingPlayer? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(PlayerId, other.PlayerId)) return false;
        if (!Equals(Rank, other.Rank)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
        if (Rank != 0) hash ^= Rank.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (PlayerId.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(PlayerId);
        }
        if (Rank != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Rank);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (PlayerId.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(PlayerId);
        }
        if (Rank != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Rank);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GekisouRankingPlayer? other)
    {
        if (other == null) return;
        if (other.PlayerId.Length != 0) PlayerId = other.PlayerId;
        if (other.Rank != 0) Rank = other.Rank;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    PlayerId = input.ReadString();
                    break;
                case 16u:
                    Rank = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
