// <auto-generated />
#nullable enable

namespace App.Protobuf.Entity;

public enum GekisouRankigType
{
    GekisouRankingTypeUnspecified = 0,
    GekisouRankingTypeScore = 1,
    GekisouRankingType01 = 2,
    GekisouRankingType02 = 3,
    GekisouRankingType03 = 4,
}
