// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class GekisouRanking : IMessage<global::App.Protobuf.Entity.GekisouRanking>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.GekisouRanking> _parser = new(() => new global::App.Protobuf.Entity.GekisouRanking());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.GekisouRanking> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GekisouRanking()
    {
    }

    public GekisouRanking(GekisouRanking other) : this()
    {
        rankingType_ = other.rankingType_;
        ranking_ = other.ranking_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GekisouRanking Clone() => new(this);

    public const int RankingTypeFieldNumber = 1;
    private GekisouRankigType rankingType_ = 0;
    public GekisouRankigType RankingType
    {
        get => rankingType_;
        set => rankingType_ = value;
    }

    public const int RankingFieldNumber = 2;
    private static readonly FieldCodec<global::App.Protobuf.Entity.GekisouRankingPlayer> _repeated_ranking_codec = FieldCodec.ForMessage(18u, global::App.Protobuf.Entity.GekisouRankingPlayer.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.GekisouRankingPlayer> ranking_ = new();
    public RepeatedField<global::App.Protobuf.Entity.GekisouRankingPlayer> Ranking => ranking_;

    public override bool Equals(object? other) => Equals(other as GekisouRanking);

    public bool Equals(GekisouRanking? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(RankingType, other.RankingType)) return false;
        if (!ranking_.Equals(other.ranking_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (RankingType != 0) hash ^= RankingType.GetHashCode();
        hash ^= ranking_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (RankingType != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteEnum((int)RankingType);
        }
        ranking_.WriteTo(output, _repeated_ranking_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (RankingType != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeEnumSize((int)RankingType);
        }
        size += ranking_.CalculateSize(_repeated_ranking_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GekisouRanking? other)
    {
        if (other == null) return;
        if (other.RankingType != 0) RankingType = other.RankingType;
        ranking_.Add(other.ranking_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    RankingType = (GekisouRankigType)input.ReadEnum();
                    break;
                case 18u:
                    ranking_.AddEntriesFrom(input, _repeated_ranking_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
