// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class InvitationProfile : IMessage<global::App.Protobuf.Entity.InvitationProfile>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.InvitationProfile> _parser = new(() => new global::App.Protobuf.Entity.InvitationProfile());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.InvitationProfile> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public InvitationProfile()
    {
    }

    public InvitationProfile(InvitationProfile other) : this()
    {
        playerProfile_ = other.playerProfile_?.Clone();
        establishmentAt_ = other.establishmentAt_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public InvitationProfile Clone() => new(this);

    public const int PlayerProfileFieldNumber = 1;
    private PlayerSimpleProfile? playerProfile_;
    public PlayerSimpleProfile? PlayerProfile
    {
        get => playerProfile_;
        set => playerProfile_ = value;
    }

    public const int EstablishmentAtFieldNumber = 2;
    private long establishmentAt_ = 0;
    public long EstablishmentAt
    {
        get => establishmentAt_;
        set => establishmentAt_ = value;
    }

    public override bool Equals(object? other) => Equals(other as InvitationProfile);

    public bool Equals(InvitationProfile? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(PlayerProfile, other.PlayerProfile)) return false;
        if (!Equals(EstablishmentAt, other.EstablishmentAt)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (PlayerProfile != null) hash ^= PlayerProfile.GetHashCode();
        if (EstablishmentAt != 0) hash ^= EstablishmentAt.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (PlayerProfile != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(PlayerProfile);
        }
        if (EstablishmentAt != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(EstablishmentAt);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (PlayerProfile != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(PlayerProfile);
        }
        if (EstablishmentAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(EstablishmentAt);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(InvitationProfile? other)
    {
        if (other == null) return;
        if (other.PlayerProfile != null)
        {
            if (PlayerProfile == null)
                PlayerProfile = other.PlayerProfile.Clone();
            else
                PlayerProfile.MergeFrom(other.PlayerProfile);
        }
        if (other.EstablishmentAt != 0) EstablishmentAt = other.EstablishmentAt;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    PlayerProfile ??= new global::App.Protobuf.Entity.PlayerSimpleProfile();
                    input.ReadMessage(PlayerProfile);
                    break;
                case 16u:
                    EstablishmentAt = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
