// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class Item : IMessage<global::App.Protobuf.Entity.Item>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.Item> _parser = new(() => new global::App.Protobuf.Entity.Item());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.Item> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public Item()
    {
    }

    public Item(Item other) : this()
    {
        masterId_ = other.masterId_;
        amount_ = other.amount_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public Item Clone() => new(this);

    public const int MasterIdFieldNumber = 1;
    private long masterId_ = 0;
    public long MasterId
    {
        get => masterId_;
        set => masterId_ = value;
    }

    public const int AmountFieldNumber = 2;
    private int amount_ = 0;
    public int Amount
    {
        get => amount_;
        set => amount_ = value;
    }

    public override bool Equals(object? other) => Equals(other as Item);

    public bool Equals(Item? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(MasterId, other.MasterId)) return false;
        if (!Equals(Amount, other.Amount)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (MasterId != 0) hash ^= MasterId.GetHashCode();
        if (Amount != 0) hash ^= Amount.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (MasterId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(MasterId);
        }
        if (Amount != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Amount);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (MasterId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(MasterId);
        }
        if (Amount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Amount);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(Item? other)
    {
        if (other == null) return;
        if (other.MasterId != 0) MasterId = other.MasterId;
        if (other.Amount != 0) Amount = other.Amount;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    MasterId = input.ReadInt64();
                    break;
                case 16u:
                    Amount = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
