// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class JudgementSummary : IMessage<global::App.Protobuf.Entity.JudgementSummary>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.JudgementSummary> _parser = new(() => new global::App.Protobuf.Entity.JudgementSummary());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.JudgementSummary> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public JudgementSummary()
    {
    }

    public JudgementSummary(JudgementSummary other) : this()
    {
        clearStatus_ = other.clearStatus_;
        soloScore_ = other.soloScore_;
        combo_ = other.combo_;
        judgementCounts_ = other.judgementCounts_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public JudgementSummary Clone() => new(this);

    public const int ClearStatusFieldNumber = 1;
    private int clearStatus_ = 0;
    public int ClearStatus
    {
        get => clearStatus_;
        set => clearStatus_ = value;
    }

    public const int SoloScoreFieldNumber = 2;
    private int soloScore_ = 0;
    public int SoloScore
    {
        get => soloScore_;
        set => soloScore_ = value;
    }

    public const int ComboFieldNumber = 3;
    private int combo_ = 0;
    public int Combo
    {
        get => combo_;
        set => combo_ = value;
    }

    public const int JudgementCountsFieldNumber = 4;
    private static readonly FieldCodec<global::App.Protobuf.Entity.JudgementCount> _repeated_judgementCounts_codec = FieldCodec.ForMessage(34u, global::App.Protobuf.Entity.JudgementCount.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.JudgementCount> judgementCounts_ = new();
    public RepeatedField<global::App.Protobuf.Entity.JudgementCount> JudgementCounts => judgementCounts_;

    public override bool Equals(object? other) => Equals(other as JudgementSummary);

    public bool Equals(JudgementSummary? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(ClearStatus, other.ClearStatus)) return false;
        if (!Equals(SoloScore, other.SoloScore)) return false;
        if (!Equals(Combo, other.Combo)) return false;
        if (!judgementCounts_.Equals(other.judgementCounts_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (ClearStatus != 0) hash ^= ClearStatus.GetHashCode();
        if (SoloScore != 0) hash ^= SoloScore.GetHashCode();
        if (Combo != 0) hash ^= Combo.GetHashCode();
        hash ^= judgementCounts_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (ClearStatus != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(ClearStatus);
        }
        if (SoloScore != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(SoloScore);
        }
        if (Combo != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(Combo);
        }
        judgementCounts_.WriteTo(output, _repeated_judgementCounts_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (ClearStatus != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(ClearStatus);
        }
        if (SoloScore != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(SoloScore);
        }
        if (Combo != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(Combo);
        }
        size += judgementCounts_.CalculateSize(_repeated_judgementCounts_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(JudgementSummary? other)
    {
        if (other == null) return;
        if (other.ClearStatus != 0) ClearStatus = other.ClearStatus;
        if (other.SoloScore != 0) SoloScore = other.SoloScore;
        if (other.Combo != 0) Combo = other.Combo;
        judgementCounts_.Add(other.judgementCounts_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    ClearStatus = input.ReadInt32();
                    break;
                case 16u:
                    SoloScore = input.ReadInt32();
                    break;
                case 24u:
                    Combo = input.ReadInt32();
                    break;
                case 34u:
                    judgementCounts_.AddEntriesFrom(input, _repeated_judgementCounts_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
