// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class JudgementCount : IMessage<global::App.Protobuf.Entity.JudgementCount>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.JudgementCount> _parser = new(() => new global::App.Protobuf.Entity.JudgementCount());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.JudgementCount> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public JudgementCount()
    {
    }

    public JudgementCount(JudgementCount other) : this()
    {
        judgement_ = other.judgement_;
        totalCount_ = other.totalCount_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public JudgementCount Clone() => new(this);

    public const int JudgementFieldNumber = 1;
    private int judgement_ = 0;
    public int Judgement
    {
        get => judgement_;
        set => judgement_ = value;
    }

    public const int TotalCountFieldNumber = 2;
    private int totalCount_ = 0;
    public int TotalCount
    {
        get => totalCount_;
        set => totalCount_ = value;
    }

    public override bool Equals(object? other) => Equals(other as JudgementCount);

    public bool Equals(JudgementCount? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Judgement, other.Judgement)) return false;
        if (!Equals(TotalCount, other.TotalCount)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Judgement != 0) hash ^= Judgement.GetHashCode();
        if (TotalCount != 0) hash ^= TotalCount.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Judgement != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Judgement);
        }
        if (TotalCount != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(TotalCount);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Judgement != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Judgement);
        }
        if (TotalCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(TotalCount);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(JudgementCount? other)
    {
        if (other == null) return;
        if (other.Judgement != 0) Judgement = other.Judgement;
        if (other.TotalCount != 0) TotalCount = other.TotalCount;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Judgement = input.ReadInt32();
                    break;
                case 16u:
                    TotalCount = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
