// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class LiveBoost : IMessage<global::App.Protobuf.Entity.LiveBoost>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.LiveBoost> _parser = new(() => new global::App.Protobuf.Entity.LiveBoost());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.LiveBoost> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public LiveBoost()
    {
    }

    public LiveBoost(LiveBoost other) : this()
    {
        amount_ = other.amount_;
        previousRecoveryAt_ = other.previousRecoveryAt_;
        dailyAdView_ = other.dailyAdView_;
        dailyFullConsumeCount_ = other.dailyFullConsumeCount_;
        lastDailyResetAt_ = other.lastDailyResetAt_;
        campaignDailyCount_ = other.campaignDailyCount_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public LiveBoost Clone() => new(this);

    public const int AmountFieldNumber = 1;
    private int amount_ = 0;
    public int Amount
    {
        get => amount_;
        set => amount_ = value;
    }

    public const int PreviousRecoveryAtFieldNumber = 2;
    private long previousRecoveryAt_ = 0;
    public long PreviousRecoveryAt
    {
        get => previousRecoveryAt_;
        set => previousRecoveryAt_ = value;
    }

    public const int DailyAdViewFieldNumber = 3;
    private int dailyAdView_ = 0;
    public int DailyAdView
    {
        get => dailyAdView_;
        set => dailyAdView_ = value;
    }

    public const int DailyFullConsumeCountFieldNumber = 4;
    private int dailyFullConsumeCount_ = 0;
    public int DailyFullConsumeCount
    {
        get => dailyFullConsumeCount_;
        set => dailyFullConsumeCount_ = value;
    }

    public const int LastDailyResetAtFieldNumber = 5;
    private long lastDailyResetAt_ = 0;
    public long LastDailyResetAt
    {
        get => lastDailyResetAt_;
        set => lastDailyResetAt_ = value;
    }

    public const int CampaignDailyCountFieldNumber = 6;
    private int campaignDailyCount_ = 0;
    public int CampaignDailyCount
    {
        get => campaignDailyCount_;
        set => campaignDailyCount_ = value;
    }

    public override bool Equals(object? other) => Equals(other as LiveBoost);

    public bool Equals(LiveBoost? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Amount, other.Amount)) return false;
        if (!Equals(PreviousRecoveryAt, other.PreviousRecoveryAt)) return false;
        if (!Equals(DailyAdView, other.DailyAdView)) return false;
        if (!Equals(DailyFullConsumeCount, other.DailyFullConsumeCount)) return false;
        if (!Equals(LastDailyResetAt, other.LastDailyResetAt)) return false;
        if (!Equals(CampaignDailyCount, other.CampaignDailyCount)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Amount != 0) hash ^= Amount.GetHashCode();
        if (PreviousRecoveryAt != 0) hash ^= PreviousRecoveryAt.GetHashCode();
        if (DailyAdView != 0) hash ^= DailyAdView.GetHashCode();
        if (DailyFullConsumeCount != 0) hash ^= DailyFullConsumeCount.GetHashCode();
        if (LastDailyResetAt != 0) hash ^= LastDailyResetAt.GetHashCode();
        if (CampaignDailyCount != 0) hash ^= CampaignDailyCount.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Amount != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Amount);
        }
        if (PreviousRecoveryAt != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(PreviousRecoveryAt);
        }
        if (DailyAdView != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(DailyAdView);
        }
        if (DailyFullConsumeCount != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt32(DailyFullConsumeCount);
        }
        if (LastDailyResetAt != 0)
        {
            output.WriteRawTag(0x28);
            output.WriteInt64(LastDailyResetAt);
        }
        if (CampaignDailyCount != 0)
        {
            output.WriteRawTag(0x30);
            output.WriteInt32(CampaignDailyCount);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Amount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Amount);
        }
        if (PreviousRecoveryAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(PreviousRecoveryAt);
        }
        if (DailyAdView != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(DailyAdView);
        }
        if (DailyFullConsumeCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt32Size(DailyFullConsumeCount);
        }
        if (LastDailyResetAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeInt64Size(LastDailyResetAt);
        }
        if (CampaignDailyCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeInt32Size(CampaignDailyCount);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(LiveBoost? other)
    {
        if (other == null) return;
        if (other.Amount != 0) Amount = other.Amount;
        if (other.PreviousRecoveryAt != 0) PreviousRecoveryAt = other.PreviousRecoveryAt;
        if (other.DailyAdView != 0) DailyAdView = other.DailyAdView;
        if (other.DailyFullConsumeCount != 0) DailyFullConsumeCount = other.DailyFullConsumeCount;
        if (other.LastDailyResetAt != 0) LastDailyResetAt = other.LastDailyResetAt;
        if (other.CampaignDailyCount != 0) CampaignDailyCount = other.CampaignDailyCount;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Amount = input.ReadInt32();
                    break;
                case 16u:
                    PreviousRecoveryAt = input.ReadInt64();
                    break;
                case 24u:
                    DailyAdView = input.ReadInt32();
                    break;
                case 32u:
                    DailyFullConsumeCount = input.ReadInt32();
                    break;
                case 40u:
                    LastDailyResetAt = input.ReadInt64();
                    break;
                case 48u:
                    CampaignDailyCount = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
