// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class LiveMusicComboReward : IMessage<global::App.Protobuf.Entity.LiveMusicComboReward>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.LiveMusicComboReward> _parser = new(() => new global::App.Protobuf.Entity.LiveMusicComboReward());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.LiveMusicComboReward> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public LiveMusicComboReward()
    {
    }

    public LiveMusicComboReward(LiveMusicComboReward other) : this()
    {
        musicId_ = other.musicId_;
        difficulty_ = other.difficulty_;
        comboRewardGained_ = other.comboRewardGained_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public LiveMusicComboReward Clone() => new(this);

    public const int MusicIdFieldNumber = 1;
    private long musicId_ = 0;
    public long MusicId
    {
        get => musicId_;
        set => musicId_ = value;
    }

    public const int DifficultyFieldNumber = 2;
    private int difficulty_ = 0;
    public int Difficulty
    {
        get => difficulty_;
        set => difficulty_ = value;
    }

    public const int ComboRewardGainedFieldNumber = 3;
    private int comboRewardGained_ = 0;
    public int ComboRewardGained
    {
        get => comboRewardGained_;
        set => comboRewardGained_ = value;
    }

    public override bool Equals(object? other) => Equals(other as LiveMusicComboReward);

    public bool Equals(LiveMusicComboReward? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(MusicId, other.MusicId)) return false;
        if (!Equals(Difficulty, other.Difficulty)) return false;
        if (!Equals(ComboRewardGained, other.ComboRewardGained)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (MusicId != 0) hash ^= MusicId.GetHashCode();
        if (Difficulty != 0) hash ^= Difficulty.GetHashCode();
        if (ComboRewardGained != 0) hash ^= ComboRewardGained.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (MusicId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(MusicId);
        }
        if (Difficulty != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Difficulty);
        }
        if (ComboRewardGained != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(ComboRewardGained);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (MusicId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(MusicId);
        }
        if (Difficulty != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Difficulty);
        }
        if (ComboRewardGained != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(ComboRewardGained);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(LiveMusicComboReward? other)
    {
        if (other == null) return;
        if (other.MusicId != 0) MusicId = other.MusicId;
        if (other.Difficulty != 0) Difficulty = other.Difficulty;
        if (other.ComboRewardGained != 0) ComboRewardGained = other.ComboRewardGained;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    MusicId = input.ReadInt64();
                    break;
                case 16u:
                    Difficulty = input.ReadInt32();
                    break;
                case 24u:
                    ComboRewardGained = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
