// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class LiveStampReward : IMessage<global::App.Protobuf.Entity.LiveStampReward>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.LiveStampReward> _parser = new(() => new global::App.Protobuf.Entity.LiveStampReward());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.LiveStampReward> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public LiveStampReward()
    {
    }

    public LiveStampReward(LiveStampReward other) : this()
    {
        liveCompleted_ = other.liveCompleted_;
        rewardGained_ = other.rewardGained_;
        lastLiveCompletedAt_ = other.lastLiveCompletedAt_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public LiveStampReward Clone() => new(this);

    public const int LiveCompletedFieldNumber = 1;
    private int liveCompleted_ = 0;
    public int LiveCompleted
    {
        get => liveCompleted_;
        set => liveCompleted_ = value;
    }

    public const int RewardGainedFieldNumber = 2;
    private int rewardGained_ = 0;
    public int RewardGained
    {
        get => rewardGained_;
        set => rewardGained_ = value;
    }

    public const int LastLiveCompletedAtFieldNumber = 3;
    private long lastLiveCompletedAt_ = 0;
    public long LastLiveCompletedAt
    {
        get => lastLiveCompletedAt_;
        set => lastLiveCompletedAt_ = value;
    }

    public override bool Equals(object? other) => Equals(other as LiveStampReward);

    public bool Equals(LiveStampReward? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(LiveCompleted, other.LiveCompleted)) return false;
        if (!Equals(RewardGained, other.RewardGained)) return false;
        if (!Equals(LastLiveCompletedAt, other.LastLiveCompletedAt)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (LiveCompleted != 0) hash ^= LiveCompleted.GetHashCode();
        if (RewardGained != 0) hash ^= RewardGained.GetHashCode();
        if (LastLiveCompletedAt != 0) hash ^= LastLiveCompletedAt.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (LiveCompleted != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(LiveCompleted);
        }
        if (RewardGained != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(RewardGained);
        }
        if (LastLiveCompletedAt != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt64(LastLiveCompletedAt);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (LiveCompleted != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(LiveCompleted);
        }
        if (RewardGained != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(RewardGained);
        }
        if (LastLiveCompletedAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt64Size(LastLiveCompletedAt);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(LiveStampReward? other)
    {
        if (other == null) return;
        if (other.LiveCompleted != 0) LiveCompleted = other.LiveCompleted;
        if (other.RewardGained != 0) RewardGained = other.RewardGained;
        if (other.LastLiveCompletedAt != 0) LastLiveCompletedAt = other.LastLiveCompletedAt;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    LiveCompleted = input.ReadInt32();
                    break;
                case 16u:
                    RewardGained = input.ReadInt32();
                    break;
                case 24u:
                    LastLiveCompletedAt = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
