// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class LiveSkip : IMessage<global::App.Protobuf.Entity.LiveSkip>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.LiveSkip> _parser = new(() => new global::App.Protobuf.Entity.LiveSkip());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.LiveSkip> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public LiveSkip()
    {
    }

    public LiveSkip(LiveSkip other) : this()
    {
        count_ = other.count_;
        lastSkip_ = other.lastSkip_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public LiveSkip Clone() => new(this);

    public const int CountFieldNumber = 1;
    private int count_ = 0;
    public int Count
    {
        get => count_;
        set => count_ = value;
    }

    public const int LastSkipFieldNumber = 2;
    private long lastSkip_ = 0;
    public long LastSkip
    {
        get => lastSkip_;
        set => lastSkip_ = value;
    }

    public override bool Equals(object? other) => Equals(other as LiveSkip);

    public bool Equals(LiveSkip? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Count, other.Count)) return false;
        if (!Equals(LastSkip, other.LastSkip)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Count != 0) hash ^= Count.GetHashCode();
        if (LastSkip != 0) hash ^= LastSkip.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Count != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Count);
        }
        if (LastSkip != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(LastSkip);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Count != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Count);
        }
        if (LastSkip != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(LastSkip);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(LiveSkip? other)
    {
        if (other == null) return;
        if (other.Count != 0) Count = other.Count;
        if (other.LastSkip != 0) LastSkip = other.LastSkip;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Count = input.ReadInt32();
                    break;
                case 16u:
                    LastSkip = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
