// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class Maintenance : IMessage<global::App.Protobuf.Entity.Maintenance>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.Maintenance> _parser = new(() => new global::App.Protobuf.Entity.Maintenance());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.Maintenance> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public Maintenance()
    {
    }

    public Maintenance(Maintenance other) : this()
    {
        id_ = other.id_;
        startAt_ = other.startAt_;
        endAt_ = other.endAt_;
        isTotal_ = other.isTotal_;
        features_ = other.features_?.Clone();
        platforms_ = other.platforms_?.Clone();
        freeText_ = other.freeText_;
        isEmergency_ = other.isEmergency_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public Maintenance Clone() => new(this);

    public const int IdFieldNumber = 1;
    private string id_ = "";
    public string Id
    {
        get => id_;
        set => id_ = value ?? "";
    }

    public const int StartAtFieldNumber = 2;
    private long startAt_ = 0;
    public long StartAt
    {
        get => startAt_;
        set => startAt_ = value;
    }

    public const int EndAtFieldNumber = 3;
    private long endAt_ = 0;
    public long EndAt
    {
        get => endAt_;
        set => endAt_ = value;
    }

    public const int IsTotalFieldNumber = 4;
    private bool isTotal_ = false;
    public bool IsTotal
    {
        get => isTotal_;
        set => isTotal_ = value;
    }

    public const int FeaturesFieldNumber = 5;
    private MaintenanceFeatures? features_;
    public MaintenanceFeatures? Features
    {
        get => features_;
        set => features_ = value;
    }

    public const int PlatformsFieldNumber = 6;
    private MaintenancePlatforms? platforms_;
    public MaintenancePlatforms? Platforms
    {
        get => platforms_;
        set => platforms_ = value;
    }

    public const int FreeTextFieldNumber = 7;
    private string freeText_ = "";
    public string FreeText
    {
        get => freeText_;
        set => freeText_ = value ?? "";
    }

    public const int IsEmergencyFieldNumber = 8;
    private bool isEmergency_ = false;
    public bool IsEmergency
    {
        get => isEmergency_;
        set => isEmergency_ = value;
    }

    public override bool Equals(object? other) => Equals(other as Maintenance);

    public bool Equals(Maintenance? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Id, other.Id)) return false;
        if (!Equals(StartAt, other.StartAt)) return false;
        if (!Equals(EndAt, other.EndAt)) return false;
        if (!Equals(IsTotal, other.IsTotal)) return false;
        if (!Equals(Features, other.Features)) return false;
        if (!Equals(Platforms, other.Platforms)) return false;
        if (!Equals(FreeText, other.FreeText)) return false;
        if (!Equals(IsEmergency, other.IsEmergency)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Id.Length != 0) hash ^= Id.GetHashCode();
        if (StartAt != 0) hash ^= StartAt.GetHashCode();
        if (EndAt != 0) hash ^= EndAt.GetHashCode();
        if (IsTotal) hash ^= IsTotal.GetHashCode();
        if (Features != null) hash ^= Features.GetHashCode();
        if (Platforms != null) hash ^= Platforms.GetHashCode();
        if (FreeText.Length != 0) hash ^= FreeText.GetHashCode();
        if (IsEmergency) hash ^= IsEmergency.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Id.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(Id);
        }
        if (StartAt != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(StartAt);
        }
        if (EndAt != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt64(EndAt);
        }
        if (IsTotal)
        {
            output.WriteRawTag(0x20);
            output.WriteBool(IsTotal);
        }
        if (Features != null)
        {
            output.WriteRawTag(0x2A);
            output.WriteMessage(Features);
        }
        if (Platforms != null)
        {
            output.WriteRawTag(0x32);
            output.WriteMessage(Platforms);
        }
        if (FreeText.Length != 0)
        {
            output.WriteRawTag(0x3A);
            output.WriteString(FreeText);
        }
        if (IsEmergency)
        {
            output.WriteRawTag(0x40);
            output.WriteBool(IsEmergency);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Id.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(Id);
        }
        if (StartAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(StartAt);
        }
        if (EndAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt64Size(EndAt);
        }
        if (IsTotal)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeBoolSize(IsTotal);
        }
        if (Features != null)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeMessageSize(Features);
        }
        if (Platforms != null)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeMessageSize(Platforms);
        }
        if (FreeText.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(7);
            size += CodedOutputStream.ComputeStringSize(FreeText);
        }
        if (IsEmergency)
        {
            size += CodedOutputStream.ComputeTagSize(8);
            size += CodedOutputStream.ComputeBoolSize(IsEmergency);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(Maintenance? other)
    {
        if (other == null) return;
        if (other.Id.Length != 0) Id = other.Id;
        if (other.StartAt != 0) StartAt = other.StartAt;
        if (other.EndAt != 0) EndAt = other.EndAt;
        if (other.IsTotal) IsTotal = other.IsTotal;
        if (other.Features != null)
        {
            if (Features == null)
                Features = other.Features.Clone();
            else
                Features.MergeFrom(other.Features);
        }
        if (other.Platforms != null)
        {
            if (Platforms == null)
                Platforms = other.Platforms.Clone();
            else
                Platforms.MergeFrom(other.Platforms);
        }
        if (other.FreeText.Length != 0) FreeText = other.FreeText;
        if (other.IsEmergency) IsEmergency = other.IsEmergency;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Id = input.ReadString();
                    break;
                case 16u:
                    StartAt = input.ReadInt64();
                    break;
                case 24u:
                    EndAt = input.ReadInt64();
                    break;
                case 32u:
                    IsTotal = input.ReadBool();
                    break;
                case 42u:
                    Features ??= new global::App.Protobuf.Entity.MaintenanceFeatures();
                    input.ReadMessage(Features);
                    break;
                case 50u:
                    Platforms ??= new global::App.Protobuf.Entity.MaintenancePlatforms();
                    input.ReadMessage(Platforms);
                    break;
                case 58u:
                    FreeText = input.ReadString();
                    break;
                case 64u:
                    IsEmergency = input.ReadBool();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
