// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class MaintenanceFeatures : IMessage<global::App.Protobuf.Entity.MaintenanceFeatures>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.MaintenanceFeatures> _parser = new(() => new global::App.Protobuf.Entity.MaintenanceFeatures());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.MaintenanceFeatures> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public MaintenanceFeatures()
    {
    }

    public MaintenanceFeatures(MaintenanceFeatures other) : this()
    {
        shop_ = other.shop_;
        gacha_ = other.gacha_;
        story_ = other.story_;
        rankMatch_ = other.rankMatch_;
        casualMatch_ = other.casualMatch_;
        circle_ = other.circle_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public MaintenanceFeatures Clone() => new(this);

    public const int ShopFieldNumber = 1;
    private bool shop_ = false;
    public bool Shop
    {
        get => shop_;
        set => shop_ = value;
    }

    public const int GachaFieldNumber = 2;
    private bool gacha_ = false;
    public bool Gacha
    {
        get => gacha_;
        set => gacha_ = value;
    }

    public const int StoryFieldNumber = 3;
    private bool story_ = false;
    public bool Story
    {
        get => story_;
        set => story_ = value;
    }

    public const int RankMatchFieldNumber = 4;
    private bool rankMatch_ = false;
    public bool RankMatch
    {
        get => rankMatch_;
        set => rankMatch_ = value;
    }

    public const int CasualMatchFieldNumber = 5;
    private bool casualMatch_ = false;
    public bool CasualMatch
    {
        get => casualMatch_;
        set => casualMatch_ = value;
    }

    public const int CircleFieldNumber = 6;
    private bool circle_ = false;
    public bool Circle
    {
        get => circle_;
        set => circle_ = value;
    }

    public override bool Equals(object? other) => Equals(other as MaintenanceFeatures);

    public bool Equals(MaintenanceFeatures? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Shop, other.Shop)) return false;
        if (!Equals(Gacha, other.Gacha)) return false;
        if (!Equals(Story, other.Story)) return false;
        if (!Equals(RankMatch, other.RankMatch)) return false;
        if (!Equals(CasualMatch, other.CasualMatch)) return false;
        if (!Equals(Circle, other.Circle)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Shop) hash ^= Shop.GetHashCode();
        if (Gacha) hash ^= Gacha.GetHashCode();
        if (Story) hash ^= Story.GetHashCode();
        if (RankMatch) hash ^= RankMatch.GetHashCode();
        if (CasualMatch) hash ^= CasualMatch.GetHashCode();
        if (Circle) hash ^= Circle.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Shop)
        {
            output.WriteRawTag(0x08);
            output.WriteBool(Shop);
        }
        if (Gacha)
        {
            output.WriteRawTag(0x10);
            output.WriteBool(Gacha);
        }
        if (Story)
        {
            output.WriteRawTag(0x18);
            output.WriteBool(Story);
        }
        if (RankMatch)
        {
            output.WriteRawTag(0x20);
            output.WriteBool(RankMatch);
        }
        if (CasualMatch)
        {
            output.WriteRawTag(0x28);
            output.WriteBool(CasualMatch);
        }
        if (Circle)
        {
            output.WriteRawTag(0x30);
            output.WriteBool(Circle);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Shop)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeBoolSize(Shop);
        }
        if (Gacha)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeBoolSize(Gacha);
        }
        if (Story)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeBoolSize(Story);
        }
        if (RankMatch)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeBoolSize(RankMatch);
        }
        if (CasualMatch)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeBoolSize(CasualMatch);
        }
        if (Circle)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeBoolSize(Circle);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(MaintenanceFeatures? other)
    {
        if (other == null) return;
        if (other.Shop) Shop = other.Shop;
        if (other.Gacha) Gacha = other.Gacha;
        if (other.Story) Story = other.Story;
        if (other.RankMatch) RankMatch = other.RankMatch;
        if (other.CasualMatch) CasualMatch = other.CasualMatch;
        if (other.Circle) Circle = other.Circle;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Shop = input.ReadBool();
                    break;
                case 16u:
                    Gacha = input.ReadBool();
                    break;
                case 24u:
                    Story = input.ReadBool();
                    break;
                case 32u:
                    RankMatch = input.ReadBool();
                    break;
                case 40u:
                    CasualMatch = input.ReadBool();
                    break;
                case 48u:
                    Circle = input.ReadBool();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
