// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class MemberCard : IMessage<global::App.Protobuf.Entity.MemberCard>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.MemberCard> _parser = new(() => new global::App.Protobuf.Entity.MemberCard());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.MemberCard> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public MemberCard()
    {
    }

    public MemberCard(MemberCard other) : this()
    {
        id_ = other.id_;
        masterId_ = other.masterId_;
        exp_ = other.exp_;
        awakeCount_ = other.awakeCount_;
        cardRank_ = other.cardRank_;
        leaderSkillLevel_ = other.leaderSkillLevel_;
        liveSkillLevel_ = other.liveSkillLevel_;
        performanceSkillLevel_ = other.performanceSkillLevel_;
        gainAt_ = other.gainAt_;
        linkSkillLevel_ = other.linkSkillLevel_;
        gekisouSkillLevel_ = other.gekisouSkillLevel_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public MemberCard Clone() => new(this);

    public const int IdFieldNumber = 1;
    private int id_ = 0;
    public int Id
    {
        get => id_;
        set => id_ = value;
    }

    public const int MasterIdFieldNumber = 2;
    private long masterId_ = 0;
    public long MasterId
    {
        get => masterId_;
        set => masterId_ = value;
    }

    public const int ExpFieldNumber = 3;
    private int exp_ = 0;
    public int Exp
    {
        get => exp_;
        set => exp_ = value;
    }

    public const int AwakeCountFieldNumber = 4;
    private int awakeCount_ = 0;
    public int AwakeCount
    {
        get => awakeCount_;
        set => awakeCount_ = value;
    }

    public const int CardRankFieldNumber = 5;
    private int cardRank_ = 0;
    public int CardRank
    {
        get => cardRank_;
        set => cardRank_ = value;
    }

    public const int LeaderSkillLevelFieldNumber = 6;
    private int leaderSkillLevel_ = 0;
    public int LeaderSkillLevel
    {
        get => leaderSkillLevel_;
        set => leaderSkillLevel_ = value;
    }

    public const int LiveSkillLevelFieldNumber = 7;
    private int liveSkillLevel_ = 0;
    public int LiveSkillLevel
    {
        get => liveSkillLevel_;
        set => liveSkillLevel_ = value;
    }

    public const int PerformanceSkillLevelFieldNumber = 8;
    private int performanceSkillLevel_ = 0;
    public int PerformanceSkillLevel
    {
        get => performanceSkillLevel_;
        set => performanceSkillLevel_ = value;
    }

    public const int GainAtFieldNumber = 9;
    private long gainAt_ = 0;
    public long GainAt
    {
        get => gainAt_;
        set => gainAt_ = value;
    }

    public const int LinkSkillLevelFieldNumber = 10;
    private int linkSkillLevel_ = 0;
    public int LinkSkillLevel
    {
        get => linkSkillLevel_;
        set => linkSkillLevel_ = value;
    }

    public const int GekisouSkillLevelFieldNumber = 11;
    private int gekisouSkillLevel_ = 0;
    public int GekisouSkillLevel
    {
        get => gekisouSkillLevel_;
        set => gekisouSkillLevel_ = value;
    }

    public override bool Equals(object? other) => Equals(other as MemberCard);

    public bool Equals(MemberCard? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Id, other.Id)) return false;
        if (!Equals(MasterId, other.MasterId)) return false;
        if (!Equals(Exp, other.Exp)) return false;
        if (!Equals(AwakeCount, other.AwakeCount)) return false;
        if (!Equals(CardRank, other.CardRank)) return false;
        if (!Equals(LeaderSkillLevel, other.LeaderSkillLevel)) return false;
        if (!Equals(LiveSkillLevel, other.LiveSkillLevel)) return false;
        if (!Equals(PerformanceSkillLevel, other.PerformanceSkillLevel)) return false;
        if (!Equals(GainAt, other.GainAt)) return false;
        if (!Equals(LinkSkillLevel, other.LinkSkillLevel)) return false;
        if (!Equals(GekisouSkillLevel, other.GekisouSkillLevel)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Id != 0) hash ^= Id.GetHashCode();
        if (MasterId != 0) hash ^= MasterId.GetHashCode();
        if (Exp != 0) hash ^= Exp.GetHashCode();
        if (AwakeCount != 0) hash ^= AwakeCount.GetHashCode();
        if (CardRank != 0) hash ^= CardRank.GetHashCode();
        if (LeaderSkillLevel != 0) hash ^= LeaderSkillLevel.GetHashCode();
        if (LiveSkillLevel != 0) hash ^= LiveSkillLevel.GetHashCode();
        if (PerformanceSkillLevel != 0) hash ^= PerformanceSkillLevel.GetHashCode();
        if (GainAt != 0) hash ^= GainAt.GetHashCode();
        if (LinkSkillLevel != 0) hash ^= LinkSkillLevel.GetHashCode();
        if (GekisouSkillLevel != 0) hash ^= GekisouSkillLevel.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Id != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Id);
        }
        if (MasterId != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(MasterId);
        }
        if (Exp != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(Exp);
        }
        if (AwakeCount != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt32(AwakeCount);
        }
        if (CardRank != 0)
        {
            output.WriteRawTag(0x28);
            output.WriteInt32(CardRank);
        }
        if (LeaderSkillLevel != 0)
        {
            output.WriteRawTag(0x30);
            output.WriteInt32(LeaderSkillLevel);
        }
        if (LiveSkillLevel != 0)
        {
            output.WriteRawTag(0x38);
            output.WriteInt32(LiveSkillLevel);
        }
        if (PerformanceSkillLevel != 0)
        {
            output.WriteRawTag(0x40);
            output.WriteInt32(PerformanceSkillLevel);
        }
        if (GainAt != 0)
        {
            output.WriteRawTag(0x48);
            output.WriteInt64(GainAt);
        }
        if (LinkSkillLevel != 0)
        {
            output.WriteRawTag(0x50);
            output.WriteInt32(LinkSkillLevel);
        }
        if (GekisouSkillLevel != 0)
        {
            output.WriteRawTag(0x58);
            output.WriteInt32(GekisouSkillLevel);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Id != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Id);
        }
        if (MasterId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(MasterId);
        }
        if (Exp != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(Exp);
        }
        if (AwakeCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt32Size(AwakeCount);
        }
        if (CardRank != 0)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeInt32Size(CardRank);
        }
        if (LeaderSkillLevel != 0)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeInt32Size(LeaderSkillLevel);
        }
        if (LiveSkillLevel != 0)
        {
            size += CodedOutputStream.ComputeTagSize(7);
            size += CodedOutputStream.ComputeInt32Size(LiveSkillLevel);
        }
        if (PerformanceSkillLevel != 0)
        {
            size += CodedOutputStream.ComputeTagSize(8);
            size += CodedOutputStream.ComputeInt32Size(PerformanceSkillLevel);
        }
        if (GainAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(9);
            size += CodedOutputStream.ComputeInt64Size(GainAt);
        }
        if (LinkSkillLevel != 0)
        {
            size += CodedOutputStream.ComputeTagSize(10);
            size += CodedOutputStream.ComputeInt32Size(LinkSkillLevel);
        }
        if (GekisouSkillLevel != 0)
        {
            size += CodedOutputStream.ComputeTagSize(11);
            size += CodedOutputStream.ComputeInt32Size(GekisouSkillLevel);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(MemberCard? other)
    {
        if (other == null) return;
        if (other.Id != 0) Id = other.Id;
        if (other.MasterId != 0) MasterId = other.MasterId;
        if (other.Exp != 0) Exp = other.Exp;
        if (other.AwakeCount != 0) AwakeCount = other.AwakeCount;
        if (other.CardRank != 0) CardRank = other.CardRank;
        if (other.LeaderSkillLevel != 0) LeaderSkillLevel = other.LeaderSkillLevel;
        if (other.LiveSkillLevel != 0) LiveSkillLevel = other.LiveSkillLevel;
        if (other.PerformanceSkillLevel != 0) PerformanceSkillLevel = other.PerformanceSkillLevel;
        if (other.GainAt != 0) GainAt = other.GainAt;
        if (other.LinkSkillLevel != 0) LinkSkillLevel = other.LinkSkillLevel;
        if (other.GekisouSkillLevel != 0) GekisouSkillLevel = other.GekisouSkillLevel;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Id = input.ReadInt32();
                    break;
                case 16u:
                    MasterId = input.ReadInt64();
                    break;
                case 24u:
                    Exp = input.ReadInt32();
                    break;
                case 32u:
                    AwakeCount = input.ReadInt32();
                    break;
                case 40u:
                    CardRank = input.ReadInt32();
                    break;
                case 48u:
                    LeaderSkillLevel = input.ReadInt32();
                    break;
                case 56u:
                    LiveSkillLevel = input.ReadInt32();
                    break;
                case 64u:
                    PerformanceSkillLevel = input.ReadInt32();
                    break;
                case 72u:
                    GainAt = input.ReadInt64();
                    break;
                case 80u:
                    LinkSkillLevel = input.ReadInt32();
                    break;
                case 88u:
                    GekisouSkillLevel = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
