// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class PagingInfo : IMessage<global::App.Protobuf.Entity.PagingInfo>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.PagingInfo> _parser = new(() => new global::App.Protobuf.Entity.PagingInfo());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.PagingInfo> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public PagingInfo()
    {
    }

    public PagingInfo(PagingInfo other) : this()
    {
        limit_ = other.limit_;
        totalCount_ = other.totalCount_;
        totalPage_ = other.totalPage_;
        currentPage_ = other.currentPage_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public PagingInfo Clone() => new(this);

    public const int LimitFieldNumber = 1;
    private long limit_ = 0;
    public long Limit
    {
        get => limit_;
        set => limit_ = value;
    }

    public const int TotalCountFieldNumber = 2;
    private long totalCount_ = 0;
    public long TotalCount
    {
        get => totalCount_;
        set => totalCount_ = value;
    }

    public const int TotalPageFieldNumber = 3;
    private uint totalPage_ = 0;
    public uint TotalPage
    {
        get => totalPage_;
        set => totalPage_ = value;
    }

    public const int CurrentPageFieldNumber = 4;
    private uint currentPage_ = 0;
    public uint CurrentPage
    {
        get => currentPage_;
        set => currentPage_ = value;
    }

    public override bool Equals(object? other) => Equals(other as PagingInfo);

    public bool Equals(PagingInfo? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Limit, other.Limit)) return false;
        if (!Equals(TotalCount, other.TotalCount)) return false;
        if (!Equals(TotalPage, other.TotalPage)) return false;
        if (!Equals(CurrentPage, other.CurrentPage)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Limit != 0) hash ^= Limit.GetHashCode();
        if (TotalCount != 0) hash ^= TotalCount.GetHashCode();
        if (TotalPage != 0) hash ^= TotalPage.GetHashCode();
        if (CurrentPage != 0) hash ^= CurrentPage.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Limit != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(Limit);
        }
        if (TotalCount != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(TotalCount);
        }
        if (TotalPage != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteUInt32(TotalPage);
        }
        if (CurrentPage != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteUInt32(CurrentPage);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Limit != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(Limit);
        }
        if (TotalCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(TotalCount);
        }
        if (TotalPage != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeUInt32Size(TotalPage);
        }
        if (CurrentPage != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeUInt32Size(CurrentPage);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(PagingInfo? other)
    {
        if (other == null) return;
        if (other.Limit != 0) Limit = other.Limit;
        if (other.TotalCount != 0) TotalCount = other.TotalCount;
        if (other.TotalPage != 0) TotalPage = other.TotalPage;
        if (other.CurrentPage != 0) CurrentPage = other.CurrentPage;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Limit = input.ReadInt64();
                    break;
                case 16u:
                    TotalCount = input.ReadInt64();
                    break;
                case 24u:
                    TotalPage = input.ReadUInt32();
                    break;
                case 32u:
                    CurrentPage = input.ReadUInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
