// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class PlayerDetailProfile : IMessage<global::App.Protobuf.Entity.PlayerDetailProfile>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.PlayerDetailProfile> _parser = new(() => new global::App.Protobuf.Entity.PlayerDetailProfile());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.PlayerDetailProfile> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public PlayerDetailProfile()
    {
    }

    public PlayerDetailProfile(PlayerDetailProfile other) : this()
    {
        id_ = other.id_;
        name_ = other.name_;
        rankExp_ = other.rankExp_;
        lastUpdatedAt_ = other.lastUpdatedAt_;
        favoriteMemberCard_ = other.favoriteMemberCard_?.Clone();
        profileId_ = other.profileId_;
        favoriteMemberCardMasterId_ = other.favoriteMemberCardMasterId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public PlayerDetailProfile Clone() => new(this);

    public const int IdFieldNumber = 1;
    private string id_ = "";
    public string Id
    {
        get => id_;
        set => id_ = value ?? "";
    }

    public const int NameFieldNumber = 2;
    private string name_ = "";
    public string Name
    {
        get => name_;
        set => name_ = value ?? "";
    }

    public const int RankExpFieldNumber = 3;
    private int rankExp_ = 0;
    public int RankExp
    {
        get => rankExp_;
        set => rankExp_ = value;
    }

    public const int LastUpdatedAtFieldNumber = 4;
    private long lastUpdatedAt_ = 0;
    public long LastUpdatedAt
    {
        get => lastUpdatedAt_;
        set => lastUpdatedAt_ = value;
    }

    public const int FavoriteMemberCardFieldNumber = 5;
    private DeckMemberCardDetail? favoriteMemberCard_;
    public DeckMemberCardDetail? FavoriteMemberCard
    {
        get => favoriteMemberCard_;
        set => favoriteMemberCard_ = value;
    }

    public const int ProfileIdFieldNumber = 6;
    private long profileId_ = 0;
    public long ProfileId
    {
        get => profileId_;
        set => profileId_ = value;
    }

    public const int FavoriteMemberCardMasterIdFieldNumber = 7;
    private long favoriteMemberCardMasterId_ = 0;
    public long FavoriteMemberCardMasterId
    {
        get => favoriteMemberCardMasterId_;
        set => favoriteMemberCardMasterId_ = value;
    }

    public override bool Equals(object? other) => Equals(other as PlayerDetailProfile);

    public bool Equals(PlayerDetailProfile? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Id, other.Id)) return false;
        if (!Equals(Name, other.Name)) return false;
        if (!Equals(RankExp, other.RankExp)) return false;
        if (!Equals(LastUpdatedAt, other.LastUpdatedAt)) return false;
        if (!Equals(FavoriteMemberCard, other.FavoriteMemberCard)) return false;
        if (!Equals(ProfileId, other.ProfileId)) return false;
        if (!Equals(FavoriteMemberCardMasterId, other.FavoriteMemberCardMasterId)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Id.Length != 0) hash ^= Id.GetHashCode();
        if (Name.Length != 0) hash ^= Name.GetHashCode();
        if (RankExp != 0) hash ^= RankExp.GetHashCode();
        if (LastUpdatedAt != 0) hash ^= LastUpdatedAt.GetHashCode();
        if (FavoriteMemberCard != null) hash ^= FavoriteMemberCard.GetHashCode();
        if (ProfileId != 0) hash ^= ProfileId.GetHashCode();
        if (FavoriteMemberCardMasterId != 0) hash ^= FavoriteMemberCardMasterId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Id.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(Id);
        }
        if (Name.Length != 0)
        {
            output.WriteRawTag(0x12);
            output.WriteString(Name);
        }
        if (RankExp != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(RankExp);
        }
        if (LastUpdatedAt != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt64(LastUpdatedAt);
        }
        if (FavoriteMemberCard != null)
        {
            output.WriteRawTag(0x2A);
            output.WriteMessage(FavoriteMemberCard);
        }
        if (ProfileId != 0)
        {
            output.WriteRawTag(0x30);
            output.WriteInt64(ProfileId);
        }
        if (FavoriteMemberCardMasterId != 0)
        {
            output.WriteRawTag(0x38);
            output.WriteInt64(FavoriteMemberCardMasterId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Id.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(Id);
        }
        if (Name.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeStringSize(Name);
        }
        if (RankExp != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(RankExp);
        }
        if (LastUpdatedAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt64Size(LastUpdatedAt);
        }
        if (FavoriteMemberCard != null)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeMessageSize(FavoriteMemberCard);
        }
        if (ProfileId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeInt64Size(ProfileId);
        }
        if (FavoriteMemberCardMasterId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(7);
            size += CodedOutputStream.ComputeInt64Size(FavoriteMemberCardMasterId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(PlayerDetailProfile? other)
    {
        if (other == null) return;
        if (other.Id.Length != 0) Id = other.Id;
        if (other.Name.Length != 0) Name = other.Name;
        if (other.RankExp != 0) RankExp = other.RankExp;
        if (other.LastUpdatedAt != 0) LastUpdatedAt = other.LastUpdatedAt;
        if (other.FavoriteMemberCard != null)
        {
            if (FavoriteMemberCard == null)
                FavoriteMemberCard = other.FavoriteMemberCard.Clone();
            else
                FavoriteMemberCard.MergeFrom(other.FavoriteMemberCard);
        }
        if (other.ProfileId != 0) ProfileId = other.ProfileId;
        if (other.FavoriteMemberCardMasterId != 0) FavoriteMemberCardMasterId = other.FavoriteMemberCardMasterId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Id = input.ReadString();
                    break;
                case 18u:
                    Name = input.ReadString();
                    break;
                case 24u:
                    RankExp = input.ReadInt32();
                    break;
                case 32u:
                    LastUpdatedAt = input.ReadInt64();
                    break;
                case 42u:
                    FavoriteMemberCard ??= new global::App.Protobuf.Entity.DeckMemberCardDetail();
                    input.ReadMessage(FavoriteMemberCard);
                    break;
                case 48u:
                    ProfileId = input.ReadInt64();
                    break;
                case 56u:
                    FavoriteMemberCardMasterId = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
