// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class PlayerMissionData : IMessage<global::App.Protobuf.Entity.PlayerMissionData>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.PlayerMissionData> _parser = new(() => new global::App.Protobuf.Entity.PlayerMissionData());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.PlayerMissionData> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public PlayerMissionData()
    {
    }

    public PlayerMissionData(PlayerMissionData other) : this()
    {
        missionCounters_ = other.missionCounters_.Clone();
        normalMissions_ = other.normalMissions_.Clone();
        limitedMissions_ = other.limitedMissions_.Clone();
        characterMissions_ = other.characterMissions_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public PlayerMissionData Clone() => new(this);

    public const int MissionCountersFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.MissionCounter> _repeated_missionCounters_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.MissionCounter.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.MissionCounter> missionCounters_ = new();
    public RepeatedField<global::App.Protobuf.Entity.MissionCounter> MissionCounters => missionCounters_;

    public const int NormalMissionsFieldNumber = 2;
    private static readonly FieldCodec<global::App.Protobuf.Entity.MissionProgress> _repeated_normalMissions_codec = FieldCodec.ForMessage(18u, global::App.Protobuf.Entity.MissionProgress.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.MissionProgress> normalMissions_ = new();
    public RepeatedField<global::App.Protobuf.Entity.MissionProgress> NormalMissions => normalMissions_;

    public const int LimitedMissionsFieldNumber = 3;
    private static readonly FieldCodec<global::App.Protobuf.Entity.MissionProgress> _repeated_limitedMissions_codec = FieldCodec.ForMessage(26u, global::App.Protobuf.Entity.MissionProgress.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.MissionProgress> limitedMissions_ = new();
    public RepeatedField<global::App.Protobuf.Entity.MissionProgress> LimitedMissions => limitedMissions_;

    public const int CharacterMissionsFieldNumber = 4;
    private static readonly FieldCodec<global::App.Protobuf.Entity.CharacterMissionReceived> _repeated_characterMissions_codec = FieldCodec.ForMessage(34u, global::App.Protobuf.Entity.CharacterMissionReceived.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.CharacterMissionReceived> characterMissions_ = new();
    public RepeatedField<global::App.Protobuf.Entity.CharacterMissionReceived> CharacterMissions => characterMissions_;

    public override bool Equals(object? other) => Equals(other as PlayerMissionData);

    public bool Equals(PlayerMissionData? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!missionCounters_.Equals(other.missionCounters_)) return false;
        if (!normalMissions_.Equals(other.normalMissions_)) return false;
        if (!limitedMissions_.Equals(other.limitedMissions_)) return false;
        if (!characterMissions_.Equals(other.characterMissions_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= missionCounters_.GetHashCode();
        hash ^= normalMissions_.GetHashCode();
        hash ^= limitedMissions_.GetHashCode();
        hash ^= characterMissions_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        missionCounters_.WriteTo(output, _repeated_missionCounters_codec);
        normalMissions_.WriteTo(output, _repeated_normalMissions_codec);
        limitedMissions_.WriteTo(output, _repeated_limitedMissions_codec);
        characterMissions_.WriteTo(output, _repeated_characterMissions_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += missionCounters_.CalculateSize(_repeated_missionCounters_codec);
        size += normalMissions_.CalculateSize(_repeated_normalMissions_codec);
        size += limitedMissions_.CalculateSize(_repeated_limitedMissions_codec);
        size += characterMissions_.CalculateSize(_repeated_characterMissions_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(PlayerMissionData? other)
    {
        if (other == null) return;
        missionCounters_.Add(other.missionCounters_);
        normalMissions_.Add(other.normalMissions_);
        limitedMissions_.Add(other.limitedMissions_);
        characterMissions_.Add(other.characterMissions_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    missionCounters_.AddEntriesFrom(input, _repeated_missionCounters_codec);
                    break;
                case 18u:
                    normalMissions_.AddEntriesFrom(input, _repeated_normalMissions_codec);
                    break;
                case 26u:
                    limitedMissions_.AddEntriesFrom(input, _repeated_limitedMissions_codec);
                    break;
                case 34u:
                    characterMissions_.AddEntriesFrom(input, _repeated_characterMissions_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
