// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class SaveCircleParams : IMessage<global::App.Protobuf.Entity.SaveCircleParams>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.SaveCircleParams> _parser = new(() => new global::App.Protobuf.Entity.SaveCircleParams());
    private UnknownFieldSet? _unknownFields;
    private int _hasBits0;

    public static MessageParser<global::App.Protobuf.Entity.SaveCircleParams> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public SaveCircleParams()
    {
    }

    public SaveCircleParams(SaveCircleParams other) : this()
    {
        _hasBits0 = other._hasBits0;
        name_ = other.name_;
        description_ = other.description_;
        joinRule_ = other.joinRule_;
        playStyle_ = other.playStyle_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public SaveCircleParams Clone() => new(this);

    public const int NameFieldNumber = 1;
    private static readonly string NameDefaultValue = "";
    private string name_ = "";
    public string Name
    {
        get => HasName ? name_ : NameDefaultValue;
        set
        {
            _hasBits0 |= 1;
            name_ = value ?? "";
        }
    }
    public bool HasName => (_hasBits0 & 1) != 0;
    public void ClearName() => _hasBits0 &= ~1;

    public const int DescriptionFieldNumber = 2;
    private static readonly string DescriptionDefaultValue = "";
    private string description_ = "";
    public string Description
    {
        get => HasDescription ? description_ : DescriptionDefaultValue;
        set
        {
            _hasBits0 |= 2;
            description_ = value ?? "";
        }
    }
    public bool HasDescription => (_hasBits0 & 2) != 0;
    public void ClearDescription() => _hasBits0 &= ~2;

    public const int JoinRuleFieldNumber = 3;
    private static readonly JoinRule JoinRuleDefaultValue = 0;
    private JoinRule joinRule_ = 0;
    public JoinRule JoinRule
    {
        get => HasJoinRule ? joinRule_ : JoinRuleDefaultValue;
        set
        {
            _hasBits0 |= 4;
            joinRule_ = value;
        }
    }
    public bool HasJoinRule => (_hasBits0 & 4) != 0;
    public void ClearJoinRule() => _hasBits0 &= ~4;

    public const int PlayStyleFieldNumber = 4;
    private static readonly PlayStyle PlayStyleDefaultValue = 0;
    private PlayStyle playStyle_ = 0;
    public PlayStyle PlayStyle
    {
        get => HasPlayStyle ? playStyle_ : PlayStyleDefaultValue;
        set
        {
            _hasBits0 |= 8;
            playStyle_ = value;
        }
    }
    public bool HasPlayStyle => (_hasBits0 & 8) != 0;
    public void ClearPlayStyle() => _hasBits0 &= ~8;

    public override bool Equals(object? other) => Equals(other as SaveCircleParams);

    public bool Equals(SaveCircleParams? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (HasName != other.HasName) return false;
        if (HasName && !Equals(Name, other.Name)) return false;
        if (HasDescription != other.HasDescription) return false;
        if (HasDescription && !Equals(Description, other.Description)) return false;
        if (HasJoinRule != other.HasJoinRule) return false;
        if (HasJoinRule && !Equals(JoinRule, other.JoinRule)) return false;
        if (HasPlayStyle != other.HasPlayStyle) return false;
        if (HasPlayStyle && !Equals(PlayStyle, other.PlayStyle)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (HasName) hash ^= Name.GetHashCode();
        if (HasDescription) hash ^= Description.GetHashCode();
        if (HasJoinRule) hash ^= JoinRule.GetHashCode();
        if (HasPlayStyle) hash ^= PlayStyle.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (HasName)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(Name);
        }
        if (HasDescription)
        {
            output.WriteRawTag(0x12);
            output.WriteString(Description);
        }
        if (HasJoinRule)
        {
            output.WriteRawTag(0x18);
            output.WriteEnum((int)JoinRule);
        }
        if (HasPlayStyle)
        {
            output.WriteRawTag(0x20);
            output.WriteEnum((int)PlayStyle);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (HasName)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(Name);
        }
        if (HasDescription)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeStringSize(Description);
        }
        if (HasJoinRule)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeEnumSize((int)JoinRule);
        }
        if (HasPlayStyle)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeEnumSize((int)PlayStyle);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(SaveCircleParams? other)
    {
        if (other == null) return;
        if (other.HasName) Name = other.Name;
        if (other.HasDescription) Description = other.Description;
        if (other.HasJoinRule) JoinRule = other.JoinRule;
        if (other.HasPlayStyle) PlayStyle = other.PlayStyle;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Name = input.ReadString();
                    break;
                case 18u:
                    Description = input.ReadString();
                    break;
                case 24u:
                    JoinRule = (JoinRule)input.ReadEnum();
                    break;
                case 32u:
                    PlayStyle = (PlayStyle)input.ReadEnum();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
