// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class SendChat : IMessage<global::App.Protobuf.Entity.SendChat>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.SendChat> _parser = new(() => new global::App.Protobuf.Entity.SendChat());
    private UnknownFieldSet? _unknownFields;
    private int _hasBits0;

    public static MessageParser<global::App.Protobuf.Entity.SendChat> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public SendChat()
    {
    }

    public SendChat(SendChat other) : this()
    {
        _hasBits0 = other._hasBits0;
        chatType_ = other.chatType_;
        friendProfileId_ = other.friendProfileId_;
        text_ = other.text_;
        stampId_ = other.stampId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public SendChat Clone() => new(this);

    public const int ChatTypeFieldNumber = 1;
    private ChatType chatType_ = 0;
    public ChatType ChatType
    {
        get => chatType_;
        set => chatType_ = value;
    }

    public const int FriendProfileIdFieldNumber = 2;
    private static readonly long FriendProfileIdDefaultValue = 0;
    private long friendProfileId_ = 0;
    public long FriendProfileId
    {
        get => HasFriendProfileId ? friendProfileId_ : FriendProfileIdDefaultValue;
        set
        {
            _hasBits0 |= 1;
            friendProfileId_ = value;
        }
    }
    public bool HasFriendProfileId => (_hasBits0 & 1) != 0;
    public void ClearFriendProfileId() => _hasBits0 &= ~1;

    public const int TextFieldNumber = 3;
    private static readonly string TextDefaultValue = "";
    private string text_ = "";
    public string Text
    {
        get => HasText ? text_ : TextDefaultValue;
        set
        {
            _hasBits0 |= 2;
            text_ = value ?? "";
        }
    }
    public bool HasText => (_hasBits0 & 2) != 0;
    public void ClearText() => _hasBits0 &= ~2;

    public const int StampIdFieldNumber = 4;
    private static readonly uint StampIdDefaultValue = 0;
    private uint stampId_ = 0;
    public uint StampId
    {
        get => HasStampId ? stampId_ : StampIdDefaultValue;
        set
        {
            _hasBits0 |= 4;
            stampId_ = value;
        }
    }
    public bool HasStampId => (_hasBits0 & 4) != 0;
    public void ClearStampId() => _hasBits0 &= ~4;

    public override bool Equals(object? other) => Equals(other as SendChat);

    public bool Equals(SendChat? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(ChatType, other.ChatType)) return false;
        if (HasFriendProfileId != other.HasFriendProfileId) return false;
        if (HasFriendProfileId && !Equals(FriendProfileId, other.FriendProfileId)) return false;
        if (HasText != other.HasText) return false;
        if (HasText && !Equals(Text, other.Text)) return false;
        if (HasStampId != other.HasStampId) return false;
        if (HasStampId && !Equals(StampId, other.StampId)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (ChatType != 0) hash ^= ChatType.GetHashCode();
        if (HasFriendProfileId) hash ^= FriendProfileId.GetHashCode();
        if (HasText) hash ^= Text.GetHashCode();
        if (HasStampId) hash ^= StampId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (ChatType != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteEnum((int)ChatType);
        }
        if (HasFriendProfileId)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(FriendProfileId);
        }
        if (HasText)
        {
            output.WriteRawTag(0x1A);
            output.WriteString(Text);
        }
        if (HasStampId)
        {
            output.WriteRawTag(0x20);
            output.WriteUInt32(StampId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (ChatType != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeEnumSize((int)ChatType);
        }
        if (HasFriendProfileId)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(FriendProfileId);
        }
        if (HasText)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeStringSize(Text);
        }
        if (HasStampId)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeUInt32Size(StampId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(SendChat? other)
    {
        if (other == null) return;
        if (other.ChatType != 0) ChatType = other.ChatType;
        if (other.HasFriendProfileId) FriendProfileId = other.FriendProfileId;
        if (other.HasText) Text = other.Text;
        if (other.HasStampId) StampId = other.StampId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    ChatType = (ChatType)input.ReadEnum();
                    break;
                case 16u:
                    FriendProfileId = input.ReadInt64();
                    break;
                case 26u:
                    Text = input.ReadString();
                    break;
                case 32u:
                    StampId = input.ReadUInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
