// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class ShopProduct : IMessage<global::App.Protobuf.Entity.ShopProduct>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.ShopProduct> _parser = new(() => new global::App.Protobuf.Entity.ShopProduct());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.ShopProduct> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public ShopProduct()
    {
    }

    public ShopProduct(ShopProduct other) : this()
    {
        shopId_ = other.shopId_;
        totalPurchaseCount_ = other.totalPurchaseCount_;
        dailyPurchaseCount_ = other.dailyPurchaseCount_;
        weeklyPurchaseCount_ = other.weeklyPurchaseCount_;
        monthlyPurchaseCount_ = other.monthlyPurchaseCount_;
        progresses_ = other.progresses_.Clone();
        expireAt_ = other.expireAt_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public ShopProduct Clone() => new(this);

    public const int ShopIdFieldNumber = 1;
    private long shopId_ = 0;
    public long ShopId
    {
        get => shopId_;
        set => shopId_ = value;
    }

    public const int TotalPurchaseCountFieldNumber = 2;
    private int totalPurchaseCount_ = 0;
    public int TotalPurchaseCount
    {
        get => totalPurchaseCount_;
        set => totalPurchaseCount_ = value;
    }

    public const int DailyPurchaseCountFieldNumber = 3;
    private int dailyPurchaseCount_ = 0;
    public int DailyPurchaseCount
    {
        get => dailyPurchaseCount_;
        set => dailyPurchaseCount_ = value;
    }

    public const int WeeklyPurchaseCountFieldNumber = 4;
    private int weeklyPurchaseCount_ = 0;
    public int WeeklyPurchaseCount
    {
        get => weeklyPurchaseCount_;
        set => weeklyPurchaseCount_ = value;
    }

    public const int MonthlyPurchaseCountFieldNumber = 5;
    private int monthlyPurchaseCount_ = 0;
    public int MonthlyPurchaseCount
    {
        get => monthlyPurchaseCount_;
        set => monthlyPurchaseCount_ = value;
    }

    public const int ProgressesFieldNumber = 6;
    private static readonly FieldCodec<global::App.Protobuf.Entity.ShopTriggerProgress> _repeated_progresses_codec = FieldCodec.ForMessage(50u, global::App.Protobuf.Entity.ShopTriggerProgress.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.ShopTriggerProgress> progresses_ = new();
    public RepeatedField<global::App.Protobuf.Entity.ShopTriggerProgress> Progresses => progresses_;

    public const int ExpireAtFieldNumber = 7;
    private long expireAt_ = 0;
    public long ExpireAt
    {
        get => expireAt_;
        set => expireAt_ = value;
    }

    public override bool Equals(object? other) => Equals(other as ShopProduct);

    public bool Equals(ShopProduct? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(ShopId, other.ShopId)) return false;
        if (!Equals(TotalPurchaseCount, other.TotalPurchaseCount)) return false;
        if (!Equals(DailyPurchaseCount, other.DailyPurchaseCount)) return false;
        if (!Equals(WeeklyPurchaseCount, other.WeeklyPurchaseCount)) return false;
        if (!Equals(MonthlyPurchaseCount, other.MonthlyPurchaseCount)) return false;
        if (!progresses_.Equals(other.progresses_)) return false;
        if (!Equals(ExpireAt, other.ExpireAt)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (ShopId != 0) hash ^= ShopId.GetHashCode();
        if (TotalPurchaseCount != 0) hash ^= TotalPurchaseCount.GetHashCode();
        if (DailyPurchaseCount != 0) hash ^= DailyPurchaseCount.GetHashCode();
        if (WeeklyPurchaseCount != 0) hash ^= WeeklyPurchaseCount.GetHashCode();
        if (MonthlyPurchaseCount != 0) hash ^= MonthlyPurchaseCount.GetHashCode();
        hash ^= progresses_.GetHashCode();
        if (ExpireAt != 0) hash ^= ExpireAt.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (ShopId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(ShopId);
        }
        if (TotalPurchaseCount != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(TotalPurchaseCount);
        }
        if (DailyPurchaseCount != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(DailyPurchaseCount);
        }
        if (WeeklyPurchaseCount != 0)
        {
            output.WriteRawTag(0x20);
            output.WriteInt32(WeeklyPurchaseCount);
        }
        if (MonthlyPurchaseCount != 0)
        {
            output.WriteRawTag(0x28);
            output.WriteInt32(MonthlyPurchaseCount);
        }
        progresses_.WriteTo(output, _repeated_progresses_codec);
        if (ExpireAt != 0)
        {
            output.WriteRawTag(0x38);
            output.WriteInt64(ExpireAt);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (ShopId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(ShopId);
        }
        if (TotalPurchaseCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(TotalPurchaseCount);
        }
        if (DailyPurchaseCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(DailyPurchaseCount);
        }
        if (WeeklyPurchaseCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(4);
            size += CodedOutputStream.ComputeInt32Size(WeeklyPurchaseCount);
        }
        if (MonthlyPurchaseCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeInt32Size(MonthlyPurchaseCount);
        }
        size += progresses_.CalculateSize(_repeated_progresses_codec);
        if (ExpireAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(7);
            size += CodedOutputStream.ComputeInt64Size(ExpireAt);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(ShopProduct? other)
    {
        if (other == null) return;
        if (other.ShopId != 0) ShopId = other.ShopId;
        if (other.TotalPurchaseCount != 0) TotalPurchaseCount = other.TotalPurchaseCount;
        if (other.DailyPurchaseCount != 0) DailyPurchaseCount = other.DailyPurchaseCount;
        if (other.WeeklyPurchaseCount != 0) WeeklyPurchaseCount = other.WeeklyPurchaseCount;
        if (other.MonthlyPurchaseCount != 0) MonthlyPurchaseCount = other.MonthlyPurchaseCount;
        progresses_.Add(other.progresses_);
        if (other.ExpireAt != 0) ExpireAt = other.ExpireAt;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    ShopId = input.ReadInt64();
                    break;
                case 16u:
                    TotalPurchaseCount = input.ReadInt32();
                    break;
                case 24u:
                    DailyPurchaseCount = input.ReadInt32();
                    break;
                case 32u:
                    WeeklyPurchaseCount = input.ReadInt32();
                    break;
                case 40u:
                    MonthlyPurchaseCount = input.ReadInt32();
                    break;
                case 50u:
                    progresses_.AddEntriesFrom(input, _repeated_progresses_codec);
                    break;
                case 56u:
                    ExpireAt = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
