// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class Stamp : IMessage<global::App.Protobuf.Entity.Stamp>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.Stamp> _parser = new(() => new global::App.Protobuf.Entity.Stamp());
    private UnknownFieldSet? _unknownFields;
    private int _hasBits0;

    public static MessageParser<global::App.Protobuf.Entity.Stamp> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public Stamp()
    {
    }

    public Stamp(Stamp other) : this()
    {
        _hasBits0 = other._hasBits0;
        id_ = other.id_;
        favorites_ = other.favorites_.Clone();
        gotAt_ = other.gotAt_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public Stamp Clone() => new(this);

    public const int IdFieldNumber = 1;
    private long id_ = 0;
    public long Id
    {
        get => id_;
        set => id_ = value;
    }

    public const int FavoritesFieldNumber = 2;
    private static readonly FieldCodec<global::App.Protobuf.Entity.FavoriteIndex> _repeated_favorites_codec = FieldCodec.ForMessage(18u, global::App.Protobuf.Entity.FavoriteIndex.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.FavoriteIndex> favorites_ = new();
    public RepeatedField<global::App.Protobuf.Entity.FavoriteIndex> Favorites => favorites_;

    public const int GotAtFieldNumber = 3;
    private static readonly long GotAtDefaultValue = 0;
    private long gotAt_ = 0;
    public long GotAt
    {
        get => HasGotAt ? gotAt_ : GotAtDefaultValue;
        set
        {
            _hasBits0 |= 1;
            gotAt_ = value;
        }
    }
    public bool HasGotAt => (_hasBits0 & 1) != 0;
    public void ClearGotAt() => _hasBits0 &= ~1;

    public override bool Equals(object? other) => Equals(other as Stamp);

    public bool Equals(Stamp? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Id, other.Id)) return false;
        if (!favorites_.Equals(other.favorites_)) return false;
        if (HasGotAt != other.HasGotAt) return false;
        if (HasGotAt && !Equals(GotAt, other.GotAt)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Id != 0) hash ^= Id.GetHashCode();
        hash ^= favorites_.GetHashCode();
        if (HasGotAt) hash ^= GotAt.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Id != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(Id);
        }
        favorites_.WriteTo(output, _repeated_favorites_codec);
        if (HasGotAt)
        {
            output.WriteRawTag(0x18);
            output.WriteInt64(GotAt);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Id != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(Id);
        }
        size += favorites_.CalculateSize(_repeated_favorites_codec);
        if (HasGotAt)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt64Size(GotAt);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(Stamp? other)
    {
        if (other == null) return;
        if (other.Id != 0) Id = other.Id;
        favorites_.Add(other.favorites_);
        if (other.HasGotAt) GotAt = other.GotAt;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Id = input.ReadInt64();
                    break;
                case 18u:
                    favorites_.AddEntriesFrom(input, _repeated_favorites_codec);
                    break;
                case 24u:
                    GotAt = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
