// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class StoryEpisode : IMessage<global::App.Protobuf.Entity.StoryEpisode>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.StoryEpisode> _parser = new(() => new global::App.Protobuf.Entity.StoryEpisode());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.StoryEpisode> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public StoryEpisode()
    {
    }

    public StoryEpisode(StoryEpisode other) : this()
    {
        episodeId_ = other.episodeId_;
        isSkipped_ = other.isSkipped_;
        lastReadAt_ = other.lastReadAt_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public StoryEpisode Clone() => new(this);

    public const int EpisodeIdFieldNumber = 1;
    private long episodeId_ = 0;
    public long EpisodeId
    {
        get => episodeId_;
        set => episodeId_ = value;
    }

    public const int IsSkippedFieldNumber = 2;
    private bool isSkipped_ = false;
    public bool IsSkipped
    {
        get => isSkipped_;
        set => isSkipped_ = value;
    }

    public const int LastReadAtFieldNumber = 3;
    private long lastReadAt_ = 0;
    public long LastReadAt
    {
        get => lastReadAt_;
        set => lastReadAt_ = value;
    }

    public override bool Equals(object? other) => Equals(other as StoryEpisode);

    public bool Equals(StoryEpisode? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(EpisodeId, other.EpisodeId)) return false;
        if (!Equals(IsSkipped, other.IsSkipped)) return false;
        if (!Equals(LastReadAt, other.LastReadAt)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (EpisodeId != 0) hash ^= EpisodeId.GetHashCode();
        if (IsSkipped) hash ^= IsSkipped.GetHashCode();
        if (LastReadAt != 0) hash ^= LastReadAt.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (EpisodeId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(EpisodeId);
        }
        if (IsSkipped)
        {
            output.WriteRawTag(0x10);
            output.WriteBool(IsSkipped);
        }
        if (LastReadAt != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt64(LastReadAt);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (EpisodeId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(EpisodeId);
        }
        if (IsSkipped)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeBoolSize(IsSkipped);
        }
        if (LastReadAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt64Size(LastReadAt);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(StoryEpisode? other)
    {
        if (other == null) return;
        if (other.EpisodeId != 0) EpisodeId = other.EpisodeId;
        if (other.IsSkipped) IsSkipped = other.IsSkipped;
        if (other.LastReadAt != 0) LastReadAt = other.LastReadAt;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    EpisodeId = input.ReadInt64();
                    break;
                case 16u:
                    IsSkipped = input.ReadBool();
                    break;
                case 24u:
                    LastReadAt = input.ReadInt64();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
