// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class SupportCard : IMessage<global::App.Protobuf.Entity.SupportCard>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.SupportCard> _parser = new(() => new global::App.Protobuf.Entity.SupportCard());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.SupportCard> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public SupportCard()
    {
    }

    public SupportCard(SupportCard other) : this()
    {
        id_ = other.id_;
        masterId_ = other.masterId_;
        exp_ = other.exp_;
        cardRank_ = other.cardRank_;
        gainAt_ = other.gainAt_;
        duplicateCount_ = other.duplicateCount_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public SupportCard Clone() => new(this);

    public const int IdFieldNumber = 1;
    private int id_ = 0;
    public int Id
    {
        get => id_;
        set => id_ = value;
    }

    public const int MasterIdFieldNumber = 2;
    private long masterId_ = 0;
    public long MasterId
    {
        get => masterId_;
        set => masterId_ = value;
    }

    public const int ExpFieldNumber = 3;
    private int exp_ = 0;
    public int Exp
    {
        get => exp_;
        set => exp_ = value;
    }

    public const int CardRankFieldNumber = 5;
    private int cardRank_ = 0;
    public int CardRank
    {
        get => cardRank_;
        set => cardRank_ = value;
    }

    public const int GainAtFieldNumber = 6;
    private long gainAt_ = 0;
    public long GainAt
    {
        get => gainAt_;
        set => gainAt_ = value;
    }

    public const int DuplicateCountFieldNumber = 7;
    private int duplicateCount_ = 0;
    public int DuplicateCount
    {
        get => duplicateCount_;
        set => duplicateCount_ = value;
    }

    public override bool Equals(object? other) => Equals(other as SupportCard);

    public bool Equals(SupportCard? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Id, other.Id)) return false;
        if (!Equals(MasterId, other.MasterId)) return false;
        if (!Equals(Exp, other.Exp)) return false;
        if (!Equals(CardRank, other.CardRank)) return false;
        if (!Equals(GainAt, other.GainAt)) return false;
        if (!Equals(DuplicateCount, other.DuplicateCount)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Id != 0) hash ^= Id.GetHashCode();
        if (MasterId != 0) hash ^= MasterId.GetHashCode();
        if (Exp != 0) hash ^= Exp.GetHashCode();
        if (CardRank != 0) hash ^= CardRank.GetHashCode();
        if (GainAt != 0) hash ^= GainAt.GetHashCode();
        if (DuplicateCount != 0) hash ^= DuplicateCount.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Id != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Id);
        }
        if (MasterId != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt64(MasterId);
        }
        if (Exp != 0)
        {
            output.WriteRawTag(0x18);
            output.WriteInt32(Exp);
        }
        if (CardRank != 0)
        {
            output.WriteRawTag(0x28);
            output.WriteInt32(CardRank);
        }
        if (GainAt != 0)
        {
            output.WriteRawTag(0x30);
            output.WriteInt64(GainAt);
        }
        if (DuplicateCount != 0)
        {
            output.WriteRawTag(0x38);
            output.WriteInt32(DuplicateCount);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Id != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Id);
        }
        if (MasterId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt64Size(MasterId);
        }
        if (Exp != 0)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeInt32Size(Exp);
        }
        if (CardRank != 0)
        {
            size += CodedOutputStream.ComputeTagSize(5);
            size += CodedOutputStream.ComputeInt32Size(CardRank);
        }
        if (GainAt != 0)
        {
            size += CodedOutputStream.ComputeTagSize(6);
            size += CodedOutputStream.ComputeInt64Size(GainAt);
        }
        if (DuplicateCount != 0)
        {
            size += CodedOutputStream.ComputeTagSize(7);
            size += CodedOutputStream.ComputeInt32Size(DuplicateCount);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(SupportCard? other)
    {
        if (other == null) return;
        if (other.Id != 0) Id = other.Id;
        if (other.MasterId != 0) MasterId = other.MasterId;
        if (other.Exp != 0) Exp = other.Exp;
        if (other.CardRank != 0) CardRank = other.CardRank;
        if (other.GainAt != 0) GainAt = other.GainAt;
        if (other.DuplicateCount != 0) DuplicateCount = other.DuplicateCount;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Id = input.ReadInt32();
                    break;
                case 16u:
                    MasterId = input.ReadInt64();
                    break;
                case 24u:
                    Exp = input.ReadInt32();
                    break;
                case 40u:
                    CardRank = input.ReadInt32();
                    break;
                case 48u:
                    GainAt = input.ReadInt64();
                    break;
                case 56u:
                    DuplicateCount = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
