// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Entity;

public sealed partial class UpdateStampFavorite : IMessage<global::App.Protobuf.Entity.UpdateStampFavorite>
{
    private static readonly MessageParser<global::App.Protobuf.Entity.UpdateStampFavorite> _parser = new(() => new global::App.Protobuf.Entity.UpdateStampFavorite());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Entity.UpdateStampFavorite> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public UpdateStampFavorite()
    {
    }

    public UpdateStampFavorite(UpdateStampFavorite other) : this()
    {
        favoriteId_ = other.favoriteId_;
        stampIds_ = other.stampIds_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public UpdateStampFavorite Clone() => new(this);

    public const int FavoriteIdFieldNumber = 1;
    private int favoriteId_ = 0;
    public int FavoriteId
    {
        get => favoriteId_;
        set => favoriteId_ = value;
    }

    public const int StampIdsFieldNumber = 2;
    private static readonly FieldCodec<long> _repeated_stampIds_codec = FieldCodec.ForInt64(18u);
    private readonly RepeatedField<long> stampIds_ = new();
    public RepeatedField<long> StampIds => stampIds_;

    public override bool Equals(object? other) => Equals(other as UpdateStampFavorite);

    public bool Equals(UpdateStampFavorite? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(FavoriteId, other.FavoriteId)) return false;
        if (!stampIds_.Equals(other.stampIds_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (FavoriteId != 0) hash ^= FavoriteId.GetHashCode();
        hash ^= stampIds_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (FavoriteId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(FavoriteId);
        }
        stampIds_.WriteTo(output, _repeated_stampIds_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (FavoriteId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(FavoriteId);
        }
        size += stampIds_.CalculateSize(_repeated_stampIds_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(UpdateStampFavorite? other)
    {
        if (other == null) return;
        if (other.FavoriteId != 0) FavoriteId = other.FavoriteId;
        stampIds_.Add(other.stampIds_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    FavoriteId = input.ReadInt32();
                    break;
                case 16u:
                case 18u:
                    stampIds_.AddEntriesFrom(input, _repeated_stampIds_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
