// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Story;

public sealed partial class ReadStoryEpisodeRequest : IMessage<global::App.Protobuf.Story.ReadStoryEpisodeRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Story.ReadStoryEpisodeRequest> _parser = new(() => new global::App.Protobuf.Story.ReadStoryEpisodeRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Story.ReadStoryEpisodeRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public ReadStoryEpisodeRequest()
    {
    }

    public ReadStoryEpisodeRequest(ReadStoryEpisodeRequest other) : this()
    {
        episodeId_ = other.episodeId_;
        isSkipped_ = other.isSkipped_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public ReadStoryEpisodeRequest Clone() => new(this);

    public const int EpisodeIdFieldNumber = 1;
    private long episodeId_;
    public long EpisodeId
    {
        get => episodeId_;
        set => episodeId_ = value;
    }

    public const int IsSkippedFieldNumber = 2;
    private bool isSkipped_;
    public bool IsSkipped
    {
        get => isSkipped_;
        set => isSkipped_ = value;
    }

    public override bool Equals(object? other) => Equals(other as ReadStoryEpisodeRequest);

    public bool Equals(ReadStoryEpisodeRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (EpisodeId != other.EpisodeId) return false;
        if (IsSkipped != other.IsSkipped) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (EpisodeId != 0L) hash ^= EpisodeId.GetHashCode();
        if (IsSkipped) hash ^= IsSkipped.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (EpisodeId != 0L)
        {
            output.WriteRawTag(0x08);
            output.WriteInt64(EpisodeId);
        }
        if (IsSkipped)
        {
            output.WriteRawTag(0x10);
            output.WriteBool(IsSkipped);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (EpisodeId != 0L)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt64Size(EpisodeId);
        }
        if (IsSkipped)
        {
            size += CodedOutputStream.ComputeTagSize(2) + 1;
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(ReadStoryEpisodeRequest? other)
    {
        if (other == null) return;
        if (other.EpisodeId != 0L) EpisodeId = other.EpisodeId;
        if (other.IsSkipped) IsSkipped = other.IsSkipped;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    EpisodeId = input.ReadInt64();
                    break;
                case 16u:
                    IsSkipped = input.ReadBool();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
