// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Story;

public sealed partial class ReadStoryEpisodeResponse : IMessage<global::App.Protobuf.Story.ReadStoryEpisodeResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Story.ReadStoryEpisodeResponse> _parser = new(() => new global::App.Protobuf.Story.ReadStoryEpisodeResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Story.ReadStoryEpisodeResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public ReadStoryEpisodeResponse()
    {
    }

    public ReadStoryEpisodeResponse(ReadStoryEpisodeResponse other) : this()
    {
        isValidBandRank_ = other.isValidBandRank_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public ReadStoryEpisodeResponse Clone() => new(this);

    public const int IsValidBandRankFieldNumber = 1;
    private bool isValidBandRank_;
    public bool IsValidBandRank
    {
        get => isValidBandRank_;
        set => isValidBandRank_ = value;
    }

    public override bool Equals(object? other) => Equals(other as ReadStoryEpisodeResponse);

    public bool Equals(ReadStoryEpisodeResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (IsValidBandRank != other.IsValidBandRank) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (IsValidBandRank) hash ^= IsValidBandRank.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (IsValidBandRank)
        {
            output.WriteRawTag(0x08);
            output.WriteBool(IsValidBandRank);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (IsValidBandRank)
        {
            size += CodedOutputStream.ComputeTagSize(1) + 1;
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(ReadStoryEpisodeResponse? other)
    {
        if (other == null) return;
        if (other.IsValidBandRank) IsValidBandRank = other.IsValidBandRank;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    IsValidBandRank = input.ReadBool();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
