// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Stamp;

public sealed partial class UpdateStampFavoritesRequest : IMessage<global::App.Protobuf.Stamp.UpdateStampFavoritesRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Stamp.UpdateStampFavoritesRequest> _parser = new(() => new global::App.Protobuf.Stamp.UpdateStampFavoritesRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Stamp.UpdateStampFavoritesRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public UpdateStampFavoritesRequest()
    {
    }

    public UpdateStampFavoritesRequest(UpdateStampFavoritesRequest other) : this()
    {
        favorites_ = other.favorites_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public UpdateStampFavoritesRequest Clone() => new(this);

    public const int FavoritesFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.UpdateStampFavorite> _repeated_favorites_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.UpdateStampFavorite.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.UpdateStampFavorite> favorites_ = new();
    public RepeatedField<global::App.Protobuf.Entity.UpdateStampFavorite> Favorites => favorites_;

    public override bool Equals(object? other) => Equals(other as UpdateStampFavoritesRequest);

    public bool Equals(UpdateStampFavoritesRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!favorites_.Equals(other.favorites_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= favorites_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        favorites_.WriteTo(output, _repeated_favorites_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += favorites_.CalculateSize(_repeated_favorites_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(UpdateStampFavoritesRequest? other)
    {
        if (other == null) return;
        favorites_.Add(other.favorites_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    favorites_.AddEntriesFrom(input, _repeated_favorites_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
