// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Stamp;

public sealed partial class UpdateStampFavoriteNameRequest : IMessage<global::App.Protobuf.Stamp.UpdateStampFavoriteNameRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Stamp.UpdateStampFavoriteNameRequest> _parser = new(() => new global::App.Protobuf.Stamp.UpdateStampFavoriteNameRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Stamp.UpdateStampFavoriteNameRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public UpdateStampFavoriteNameRequest()
    {
    }

    public UpdateStampFavoriteNameRequest(UpdateStampFavoriteNameRequest other) : this()
    {
        favoriteId_ = other.favoriteId_;
        name_ = other.name_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public UpdateStampFavoriteNameRequest Clone() => new(this);

    public const int FavoriteIdFieldNumber = 1;
    private int favoriteId_ = 0;
    public int FavoriteId
    {
        get => favoriteId_;
        set => favoriteId_ = value;
    }

    public const int NameFieldNumber = 2;
    private string name_ = "";
    public string Name
    {
        get => name_;
        set => name_ = value ?? "";
    }

    public override bool Equals(object? other) => Equals(other as UpdateStampFavoriteNameRequest);

    public bool Equals(UpdateStampFavoriteNameRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(FavoriteId, other.FavoriteId)) return false;
        if (!Equals(Name, other.Name)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (FavoriteId != 0) hash ^= FavoriteId.GetHashCode();
        if (Name.Length != 0) hash ^= Name.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (FavoriteId != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(FavoriteId);
        }
        if (Name.Length != 0)
        {
            output.WriteRawTag(0x12);
            output.WriteString(Name);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (FavoriteId != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(FavoriteId);
        }
        if (Name.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeStringSize(Name);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(UpdateStampFavoriteNameRequest? other)
    {
        if (other == null) return;
        if (other.FavoriteId != 0) FavoriteId = other.FavoriteId;
        if (other.Name.Length != 0) Name = other.Name;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    FavoriteId = input.ReadInt32();
                    break;
                case 18u:
                    Name = input.ReadString();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
