// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Present;

public sealed partial class FetchResponse : IMessage<global::App.Protobuf.Present.FetchResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Present.FetchResponse> _parser = new(() => new global::App.Protobuf.Present.FetchResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Present.FetchResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public FetchResponse()
    {
    }

    public FetchResponse(FetchResponse other) : this()
    {
        presents_ = other.presents_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public FetchResponse Clone() => new(this);

    public const int PresentsFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.Present> _repeated_presents_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.Present.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.Present> presents_ = new();
    public RepeatedField<global::App.Protobuf.Entity.Present> Presents => presents_;

    public override bool Equals(object? other) => Equals(other as FetchResponse);

    public bool Equals(FetchResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!presents_.Equals(other.presents_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= presents_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        presents_.WriteTo(output, _repeated_presents_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += presents_.CalculateSize(_repeated_presents_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(FetchResponse? other)
    {
        if (other == null) return;
        presents_.Add(other.presents_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    presents_.AddEntriesFrom(input, _repeated_presents_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
