// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Present;

public sealed partial class OpenRequest : IMessage<global::App.Protobuf.Present.OpenRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Present.OpenRequest> _parser = new(() => new global::App.Protobuf.Present.OpenRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Present.OpenRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public OpenRequest() { }

    public OpenRequest(OpenRequest other) : this()
    {
        presentIds_ = other.presentIds_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public OpenRequest Clone() => new(this);

    public const int PresentIdsFieldNumber = 1;
    private static readonly FieldCodec<ulong> _repeated_presentIds_codec = FieldCodec.ForUInt64(10u);
    private readonly RepeatedField<ulong> presentIds_ = new();
    public RepeatedField<ulong> PresentIds => presentIds_;

    public override bool Equals(object? other) => Equals(other as OpenRequest);

    public bool Equals(OpenRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return presentIds_.Equals(other.presentIds_) && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1 ^ presentIds_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        presentIds_.WriteTo(output, _repeated_presentIds_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = presentIds_.CalculateSize(_repeated_presentIds_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(OpenRequest? other)
    {
        if (other == null) return;
        presentIds_.Add(other.presentIds_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 8u || tag == 10u) presentIds_.AddEntriesFrom(input, _repeated_presentIds_codec);
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
