// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Present;

public sealed partial class OpenResponse : IMessage<global::App.Protobuf.Present.OpenResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Present.OpenResponse> _parser = new(() => new global::App.Protobuf.Present.OpenResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Present.OpenResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public OpenResponse() { }

    public OpenResponse(OpenResponse other) : this()
    {
        unreceived_ = other.unreceived_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public OpenResponse Clone() => new(this);

    public const int UnreceivedFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.PresentUnreceived> _repeated_unreceived_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.PresentUnreceived.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.PresentUnreceived> unreceived_ = new();
    public RepeatedField<global::App.Protobuf.Entity.PresentUnreceived> Unreceived => unreceived_;

    public override bool Equals(object? other) => Equals(other as OpenResponse);

    public bool Equals(OpenResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return unreceived_.Equals(other.unreceived_) && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1 ^ unreceived_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        unreceived_.WriteTo(output, _repeated_unreceived_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = unreceived_.CalculateSize(_repeated_unreceived_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(OpenResponse? other)
    {
        if (other == null) return;
        unreceived_.Add(other.unreceived_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) unreceived_.AddEntriesFrom(input, _repeated_unreceived_codec);
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
