// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Present;

public sealed partial class UpdateLoginbonusResponse : IMessage<global::App.Protobuf.Present.UpdateLoginbonusResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Present.UpdateLoginbonusResponse> _parser = new(() => new global::App.Protobuf.Present.UpdateLoginbonusResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Present.UpdateLoginbonusResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public UpdateLoginbonusResponse()
    {
    }

    public UpdateLoginbonusResponse(UpdateLoginbonusResponse other) : this()
    {
        received_ = other.received_.Clone();
        notReceived_ = other.notReceived_.Clone();
        notification_ = other.notification_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public UpdateLoginbonusResponse Clone() => new(this);

    public const int ReceivedFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.LoginBonusSheet> _repeated_received_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.LoginBonusSheet.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.LoginBonusSheet> received_ = new();
    public RepeatedField<global::App.Protobuf.Entity.LoginBonusSheet> Received => received_;

    public const int NotReceivedFieldNumber = 2;
    private static readonly FieldCodec<global::App.Protobuf.Entity.LoginBonusSheet> _repeated_notReceived_codec = FieldCodec.ForMessage(18u, global::App.Protobuf.Entity.LoginBonusSheet.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.LoginBonusSheet> notReceived_ = new();
    public RepeatedField<global::App.Protobuf.Entity.LoginBonusSheet> NotReceived => notReceived_;

    public const int NotificationFieldNumber = 3;
    private global::App.Protobuf.Entity.Notification? notification_;
    public global::App.Protobuf.Entity.Notification? Notification
    {
        get => notification_;
        set => notification_ = value;
    }

    public override bool Equals(object? other) => Equals(other as UpdateLoginbonusResponse);

    public bool Equals(UpdateLoginbonusResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!received_.Equals(other.received_)) return false;
        if (!notReceived_.Equals(other.notReceived_)) return false;
        if (!Equals(Notification, other.Notification)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= received_.GetHashCode();
        hash ^= notReceived_.GetHashCode();
        if (notification_ != null) hash ^= notification_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        received_.WriteTo(output, _repeated_received_codec);
        notReceived_.WriteTo(output, _repeated_notReceived_codec);
        if (notification_ != null)
        {
            output.WriteRawTag(0x1a);
            output.WriteMessage(Notification);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += received_.CalculateSize(_repeated_received_codec);
        size += notReceived_.CalculateSize(_repeated_notReceived_codec);
        if (notification_ != null)
        {
            size += CodedOutputStream.ComputeTagSize(3);
            size += CodedOutputStream.ComputeMessageSize(Notification);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(UpdateLoginbonusResponse? other)
    {
        if (other == null) return;
        received_.Add(other.received_);
        notReceived_.Add(other.notReceived_);
        if (other.Notification != null)
        {
            if (Notification == null)
                Notification = other.Notification.Clone();
            else
                Notification.MergeFrom(other.Notification);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    received_.AddEntriesFrom(input, _repeated_received_codec);
                    break;
                case 18u:
                    notReceived_.AddEntriesFrom(input, _repeated_notReceived_codec);
                    break;
                case 26u:
                    Notification ??= new global::App.Protobuf.Entity.Notification();
                    input.ReadMessage(Notification);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
