// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleInvitation;

public sealed partial class GetCircleInvitationRecommendListResponse : IMessage<global::App.Protobuf.CircleInvitation.GetCircleInvitationRecommendListResponse>
{
    private static readonly MessageParser<global::App.Protobuf.CircleInvitation.GetCircleInvitationRecommendListResponse> _parser = new(() => new global::App.Protobuf.CircleInvitation.GetCircleInvitationRecommendListResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.CircleInvitation.GetCircleInvitationRecommendListResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetCircleInvitationRecommendListResponse() { }

    public GetCircleInvitationRecommendListResponse(GetCircleInvitationRecommendListResponse other) : this()
    {
        playerBasicProfiles_ = other.playerBasicProfiles_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetCircleInvitationRecommendListResponse Clone() => new(this);

    public const int PlayerBasicProfilesFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.PlayerSimpleProfile> _repeated_playerBasicProfiles_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.PlayerSimpleProfile.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.PlayerSimpleProfile> playerBasicProfiles_ = new();
    public RepeatedField<global::App.Protobuf.Entity.PlayerSimpleProfile> PlayerBasicProfiles => playerBasicProfiles_;

    public override bool Equals(object? other) => Equals(other as GetCircleInvitationRecommendListResponse);

    public bool Equals(GetCircleInvitationRecommendListResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return playerBasicProfiles_.Equals(other.playerBasicProfiles_) && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= playerBasicProfiles_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        playerBasicProfiles_.WriteTo(output, _repeated_playerBasicProfiles_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = playerBasicProfiles_.CalculateSize(_repeated_playerBasicProfiles_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetCircleInvitationRecommendListResponse? other)
    {
        if (other == null) return;
        playerBasicProfiles_.Add(other.playerBasicProfiles_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) playerBasicProfiles_.AddEntriesFrom(input, _repeated_playerBasicProfiles_codec);
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
