// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleInvitation;

public sealed partial class GetInvitablePlayerResponse : IMessage<global::App.Protobuf.CircleInvitation.GetInvitablePlayerResponse>
{
    private static readonly MessageParser<global::App.Protobuf.CircleInvitation.GetInvitablePlayerResponse> _parser = new(() => new global::App.Protobuf.CircleInvitation.GetInvitablePlayerResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.CircleInvitation.GetInvitablePlayerResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetInvitablePlayerResponse() { }

    public GetInvitablePlayerResponse(GetInvitablePlayerResponse other) : this()
    {
        playerBasicProfile_ = other.playerBasicProfile_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetInvitablePlayerResponse Clone() => new(this);

    public const int PlayerBasicProfileFieldNumber = 1;
    private global::App.Protobuf.Entity.PlayerSimpleProfile? playerBasicProfile_;
    public global::App.Protobuf.Entity.PlayerSimpleProfile? PlayerBasicProfile
    {
        get => playerBasicProfile_;
        set => playerBasicProfile_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GetInvitablePlayerResponse);

    public bool Equals(GetInvitablePlayerResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(PlayerBasicProfile, other.PlayerBasicProfile)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (PlayerBasicProfile != null) hash ^= PlayerBasicProfile.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (PlayerBasicProfile != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(PlayerBasicProfile);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (PlayerBasicProfile != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(PlayerBasicProfile);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetInvitablePlayerResponse? other)
    {
        if (other == null) return;
        if (other.PlayerBasicProfile != null)
        {
            if (PlayerBasicProfile == null)
                PlayerBasicProfile = other.PlayerBasicProfile.Clone();
            else
                PlayerBasicProfile.MergeFrom(other.PlayerBasicProfile);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u)
            {
                PlayerBasicProfile ??= new global::App.Protobuf.Entity.PlayerSimpleProfile();
                input.ReadMessage(PlayerBasicProfile);
            }
            else
            {
                _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
        }
    }
}
