// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleInvitation;

public sealed partial class GetInvitationListResponse : IMessage<global::App.Protobuf.CircleInvitation.GetInvitationListResponse>
{
    private static readonly MessageParser<global::App.Protobuf.CircleInvitation.GetInvitationListResponse> _parser = new(() => new global::App.Protobuf.CircleInvitation.GetInvitationListResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.CircleInvitation.GetInvitationListResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetInvitationListResponse() { }

    public GetInvitationListResponse(GetInvitationListResponse other) : this()
    {
        invitations_ = other.invitations_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetInvitationListResponse Clone() => new(this);

    public const int InvitationsFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.CircleInvitation> _repeated_invitations_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.CircleInvitation.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.CircleInvitation> invitations_ = new();
    public RepeatedField<global::App.Protobuf.Entity.CircleInvitation> Invitations => invitations_;

    public override bool Equals(object? other) => Equals(other as GetInvitationListResponse);

    public bool Equals(GetInvitationListResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return invitations_.Equals(other.invitations_) && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= invitations_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        invitations_.WriteTo(output, _repeated_invitations_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = invitations_.CalculateSize(_repeated_invitations_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetInvitationListResponse? other)
    {
        if (other == null) return;
        invitations_.Add(other.invitations_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) invitations_.AddEntriesFrom(input, _repeated_invitations_codec);
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
