// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleInvitation;

public sealed partial class InviteCircleRequest : IMessage<global::App.Protobuf.CircleInvitation.InviteCircleRequest>
{
    private static readonly MessageParser<global::App.Protobuf.CircleInvitation.InviteCircleRequest> _parser = new(() => new global::App.Protobuf.CircleInvitation.InviteCircleRequest());
    private UnknownFieldSet? _unknownFields;
    private int _hasBits0;

    public static MessageParser<global::App.Protobuf.CircleInvitation.InviteCircleRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public InviteCircleRequest() { }

    public InviteCircleRequest(InviteCircleRequest other) : this()
    {
        _hasBits0 = other._hasBits0;
        playerId_ = other.playerId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public InviteCircleRequest Clone() => new(this);

    public const int PlayerIdFieldNumber = 1;
    private static readonly string PlayerIdDefaultValue = "";
    private string playerId_ = "";
    public string PlayerId
    {
        get => HasPlayerId ? playerId_ : PlayerIdDefaultValue;
        set
        {
            _hasBits0 |= 1;
            playerId_ = value ?? "";
        }
    }
    public bool HasPlayerId => (_hasBits0 & 1) != 0;
    public void ClearPlayerId() => _hasBits0 &= ~1;

    public override bool Equals(object? other) => Equals(other as InviteCircleRequest);

    public bool Equals(InviteCircleRequest? other) => other != null &&
        (ReferenceEquals(this, other) ||
         HasPlayerId == other.HasPlayerId &&
         (!HasPlayerId || PlayerId == other.PlayerId) &&
         Equals(_unknownFields, other._unknownFields));

    public override int GetHashCode() => (HasPlayerId ? PlayerId.GetHashCode() : 1) ^ (_unknownFields?.GetHashCode() ?? 0);

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (HasPlayerId)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(PlayerId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize() => (HasPlayerId ? CodedOutputStream.ComputeTagSize(1) + CodedOutputStream.ComputeStringSize(PlayerId) : 0) + (_unknownFields?.CalculateSize() ?? 0);

    public void MergeFrom(InviteCircleRequest? other)
    {
        if (other == null) return;
        if (other.HasPlayerId) PlayerId = other.PlayerId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) PlayerId = input.ReadString();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
