// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Shop;

public sealed partial class SaveBirthRequest : IMessage<global::App.Protobuf.Shop.SaveBirthRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Shop.SaveBirthRequest> _parser = new(() => new global::App.Protobuf.Shop.SaveBirthRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Shop.SaveBirthRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public SaveBirthRequest()
    {
    }

    public SaveBirthRequest(SaveBirthRequest other) : this()
    {
        year_ = other.year_;
        month_ = other.month_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public SaveBirthRequest Clone() => new(this);

    public const int YearFieldNumber = 1;
    private int year_;
    public int Year
    {
        get => year_;
        set => year_ = value;
    }

    public const int MonthFieldNumber = 2;
    private int month_;
    public int Month
    {
        get => month_;
        set => month_ = value;
    }

    public override bool Equals(object? other) => Equals(other as SaveBirthRequest);

    public bool Equals(SaveBirthRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (Year != other.Year) return false;
        if (Month != other.Month) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Year != 0) hash ^= Year.GetHashCode();
        if (Month != 0) hash ^= Month.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Year != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteInt32(Year);
        }
        if (Month != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(Month);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Year != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeInt32Size(Year);
        }
        if (Month != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(Month);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(SaveBirthRequest? other)
    {
        if (other == null) return;
        if (other.Year != 0) Year = other.Year;
        if (other.Month != 0) Month = other.Month;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    Year = input.ReadInt32();
                    break;
                case 16u:
                    Month = input.ReadInt32();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
