// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Deck;

public sealed partial class SaveDecksResponse : IMessage<global::App.Protobuf.Deck.SaveDecksResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Deck.SaveDecksResponse> _parser = new(() => new global::App.Protobuf.Deck.SaveDecksResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Deck.SaveDecksResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public SaveDecksResponse()
    {
    }

    public SaveDecksResponse(SaveDecksResponse other) : this()
    {
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public SaveDecksResponse Clone() => new(this);

    public override bool Equals(object? other) => Equals(other as SaveDecksResponse);

    public bool Equals(SaveDecksResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(SaveDecksResponse? other)
    {
        if (other == null) return;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
