// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Masterdata;

public sealed partial class VersionResponse : IMessage<global::App.Protobuf.Masterdata.VersionResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Masterdata.VersionResponse> _parser = new(() => new global::App.Protobuf.Masterdata.VersionResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Masterdata.VersionResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public VersionResponse()
    {
    }

    public VersionResponse(VersionResponse other) : this()
    {
        version_ = other.version_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public VersionResponse Clone() => new(this);

    public const int VersionFieldNumber = 1;
    private string version_ = "";
    public string Version
    {
        get => version_;
        set => version_ = value ?? "";
    }

    public override bool Equals(object? other) => Equals(other as VersionResponse);

    public bool Equals(VersionResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Version, other.Version)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Version.Length != 0) hash ^= Version.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Version.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(Version);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Version.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(Version);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(VersionResponse? other)
    {
        if (other == null) return;
        if (other.Version.Length != 0) Version = other.Version;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Version = input.ReadString();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
