// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.CircleRanking;

public sealed partial class GetCircleRankingResponse : IMessage<global::App.Protobuf.CircleRanking.GetCircleRankingResponse>
{
    private static readonly MessageParser<global::App.Protobuf.CircleRanking.GetCircleRankingResponse> _parser = new(() => new global::App.Protobuf.CircleRanking.GetCircleRankingResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.CircleRanking.GetCircleRankingResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetCircleRankingResponse() { }

    public GetCircleRankingResponse(GetCircleRankingResponse other) : this()
    {
        circleRanking_ = other.circleRanking_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetCircleRankingResponse Clone() => new(this);

    public const int CircleRankingFieldNumber = 1;
    private ulong circleRanking_;
    public ulong CircleRanking
    {
        get => circleRanking_;
        set => circleRanking_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GetCircleRankingResponse);

    public bool Equals(GetCircleRankingResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return CircleRanking == other.CircleRanking && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (CircleRanking != 0UL) hash ^= CircleRanking.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (CircleRanking != 0UL)
        {
            output.WriteRawTag(0x08);
            output.WriteUInt64(CircleRanking);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (CircleRanking != 0UL)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeUInt64Size(CircleRanking);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetCircleRankingResponse? other)
    {
        if (other == null) return;
        if (other.CircleRanking != 0UL) CircleRanking = other.CircleRanking;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 8u) CircleRanking = input.ReadUInt64();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
