// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Announcement;

public sealed partial class GetListResponse : IMessage<global::App.Protobuf.Announcement.GetListResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Announcement.GetListResponse> _parser = new(() => new global::App.Protobuf.Announcement.GetListResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Announcement.GetListResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetListResponse()
    {
    }

    public GetListResponse(GetListResponse other) : this()
    {
        announcements_ = other.announcements_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetListResponse Clone() => new(this);

    public const int AnnouncementsFieldNumber = 1;
    private static readonly FieldCodec<global::App.Protobuf.Entity.Announcement> _repeated_announcements_codec = FieldCodec.ForMessage(10u, global::App.Protobuf.Entity.Announcement.Parser);
    private readonly RepeatedField<global::App.Protobuf.Entity.Announcement> announcements_ = new();
    public RepeatedField<global::App.Protobuf.Entity.Announcement> Announcements => announcements_;

    public override bool Equals(object? other) => Equals(other as GetListResponse);

    public bool Equals(GetListResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!announcements_.Equals(other.announcements_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        hash ^= announcements_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        announcements_.WriteTo(output, _repeated_announcements_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        size += announcements_.CalculateSize(_repeated_announcements_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetListResponse? other)
    {
        if (other == null) return;
        announcements_.Add(other.announcements_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    announcements_.AddEntriesFrom(input, _repeated_announcements_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
