// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Announcement;

public sealed partial class GetListRequest : IMessage<global::App.Protobuf.Announcement.GetListRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Announcement.GetListRequest> _parser = new(() => new global::App.Protobuf.Announcement.GetListRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Announcement.GetListRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetListRequest()
    {
    }

    public GetListRequest(GetListRequest other) : this()
    {
        selectedTab_ = other.selectedTab_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetListRequest Clone() => new(this);

    public const int SelectedTabFieldNumber = 1;
    private Tab selectedTab_ = 0;
    public Tab SelectedTab
    {
        get => selectedTab_;
        set => selectedTab_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GetListRequest);

    public bool Equals(GetListRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(SelectedTab, other.SelectedTab)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (SelectedTab != 0) hash ^= SelectedTab.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (SelectedTab != 0)
        {
            output.WriteRawTag(0x08);
            output.WriteEnum((int)SelectedTab);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (SelectedTab != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeEnumSize((int)SelectedTab);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetListRequest? other)
    {
        if (other == null) return;
        if (other.SelectedTab != 0) SelectedTab = other.SelectedTab;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 8u:
                    SelectedTab = (Tab)input.ReadEnum();
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
