// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Announcement;

public sealed partial class GetResponse : IMessage<global::App.Protobuf.Announcement.GetResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Announcement.GetResponse> _parser = new(() => new global::App.Protobuf.Announcement.GetResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Announcement.GetResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public GetResponse() { }

    public GetResponse(GetResponse other) : this()
    {
        announcement_ = other.announcement_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public GetResponse Clone() => new(this);

    public const int AnnouncementFieldNumber = 1;
    private global::App.Protobuf.Entity.Announcement? announcement_;
    public global::App.Protobuf.Entity.Announcement? Announcement
    {
        get => announcement_;
        set => announcement_ = value;
    }

    public override bool Equals(object? other) => Equals(other as GetResponse);

    public bool Equals(GetResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return Equals(Announcement, other.Announcement) && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Announcement != null) hash ^= Announcement.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Announcement != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(Announcement);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Announcement != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(Announcement);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(GetResponse? other)
    {
        if (other == null) return;
        if (other.Announcement != null)
        {
            if (Announcement == null) Announcement = other.Announcement.Clone();
            else Announcement.MergeFrom(other.Announcement);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u)
            {
                Announcement ??= new global::App.Protobuf.Entity.Announcement();
                input.ReadMessage(Announcement);
            }
            else
            {
                _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
        }
    }
}
