// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Friend;

public sealed partial class FriendRequestWithdrawalResponse : IMessage<global::App.Protobuf.Friend.FriendRequestWithdrawalResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Friend.FriendRequestWithdrawalResponse> _parser = new(() => new global::App.Protobuf.Friend.FriendRequestWithdrawalResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Friend.FriendRequestWithdrawalResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public FriendRequestWithdrawalResponse() { }

    public FriendRequestWithdrawalResponse(FriendRequestWithdrawalResponse other) : this()
    {
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public FriendRequestWithdrawalResponse Clone() => new(this);

    public override bool Equals(object? other) => Equals(other as FriendRequestWithdrawalResponse);

    public bool Equals(FriendRequestWithdrawalResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode() => _unknownFields?.GetHashCode() ?? 1;

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output) => _unknownFields?.WriteTo(output);

    public int CalculateSize() => _unknownFields?.CalculateSize() ?? 0;

    public void MergeFrom(FriendRequestWithdrawalResponse? other)
    {
        if (other == null) return;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        while (input.ReadTag() != 0)
            _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
    }
}
