// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Friend;

public sealed partial class FriendRequestWithdrawalRequest : IMessage<global::App.Protobuf.Friend.FriendRequestWithdrawalRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Friend.FriendRequestWithdrawalRequest> _parser = new(() => new global::App.Protobuf.Friend.FriendRequestWithdrawalRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Friend.FriendRequestWithdrawalRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public FriendRequestWithdrawalRequest() { }

    public FriendRequestWithdrawalRequest(FriendRequestWithdrawalRequest other) : this()
    {
        targetPlayerId_ = other.targetPlayerId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public FriendRequestWithdrawalRequest Clone() => new(this);

    public const int TargetPlayerIdFieldNumber = 1;
    private string targetPlayerId_ = "";
    public string TargetPlayerId
    {
        get => targetPlayerId_;
        set => targetPlayerId_ = value ?? "";
    }

    public override bool Equals(object? other) => Equals(other as FriendRequestWithdrawalRequest);

    public bool Equals(FriendRequestWithdrawalRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return TargetPlayerId == other.TargetPlayerId && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (TargetPlayerId.Length != 0) hash ^= TargetPlayerId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (TargetPlayerId.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(TargetPlayerId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (TargetPlayerId.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(TargetPlayerId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(FriendRequestWithdrawalRequest? other)
    {
        if (other == null) return;
        if (other.TargetPlayerId.Length != 0) TargetPlayerId = other.TargetPlayerId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) TargetPlayerId = input.ReadString();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
