// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Friend;

public sealed partial class FriendUnlinkRequest : IMessage<global::App.Protobuf.Friend.FriendUnlinkRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Friend.FriendUnlinkRequest> _parser = new(() => new global::App.Protobuf.Friend.FriendUnlinkRequest());
    private UnknownFieldSet? _unknownFields;
    public static MessageParser<global::App.Protobuf.Friend.FriendUnlinkRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;
    public FriendUnlinkRequest() { }
    public FriendUnlinkRequest(FriendUnlinkRequest other) : this()
    {
        friendPlayerId_ = other.friendPlayerId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }
    public FriendUnlinkRequest Clone() => new(this);
    public const int FriendPlayerIdFieldNumber = 1;
    private string friendPlayerId_ = "";
    public string FriendPlayerId { get => friendPlayerId_; set => friendPlayerId_ = value ?? ""; }
    public override bool Equals(object? other) => Equals(other as FriendUnlinkRequest);
    public bool Equals(FriendUnlinkRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return FriendPlayerId == other.FriendPlayerId && Equals(_unknownFields, other._unknownFields);
    }
    public override int GetHashCode()
    {
        var hash = 1;
        if (FriendPlayerId.Length != 0) hash ^= FriendPlayerId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }
    public override string ToString() => base.ToString() ?? string.Empty;
    public void WriteTo(CodedOutputStream output)
    {
        if (FriendPlayerId.Length != 0) { output.WriteRawTag(0x0A); output.WriteString(FriendPlayerId); }
        _unknownFields?.WriteTo(output);
    }
    public int CalculateSize()
    {
        var size = 0;
        if (FriendPlayerId.Length != 0) { size += CodedOutputStream.ComputeTagSize(1); size += CodedOutputStream.ComputeStringSize(FriendPlayerId); }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }
    public void MergeFrom(FriendUnlinkRequest? other)
    {
        if (other == null) return;
        if (other.FriendPlayerId.Length != 0) FriendPlayerId = other.FriendPlayerId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }
    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) FriendPlayerId = input.ReadString();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
