// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Collections;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Friend;

public sealed partial class PlayerReportRequest : IMessage<global::App.Protobuf.Friend.PlayerReportRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Friend.PlayerReportRequest> _parser = new(() => new global::App.Protobuf.Friend.PlayerReportRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Friend.PlayerReportRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public PlayerReportRequest()
    {
    }

    public PlayerReportRequest(PlayerReportRequest other) : this()
    {
        targetPlayerId_ = other.targetPlayerId_;
        reportType_ = other.reportType_;
        reportIds_ = other.reportIds_.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public PlayerReportRequest Clone() => new(this);

    public const int TargetPlayerIdFieldNumber = 1;
    private string targetPlayerId_ = "";
    public string TargetPlayerId
    {
        get => targetPlayerId_;
        set => targetPlayerId_ = value ?? "";
    }

    public const int ReportTypeFieldNumber = 2;
    private int reportType_ = 0;
    public int ReportType
    {
        get => reportType_;
        set => reportType_ = value;
    }

    public const int ReportIdsFieldNumber = 3;
    private static readonly FieldCodec<long> _repeated_reportIds_codec = FieldCodec.ForInt64(26u);
    private readonly RepeatedField<long> reportIds_ = new();
    public RepeatedField<long> ReportIds => reportIds_;

    public override bool Equals(object? other) => Equals(other as PlayerReportRequest);

    public bool Equals(PlayerReportRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(TargetPlayerId, other.TargetPlayerId)) return false;
        if (!Equals(ReportType, other.ReportType)) return false;
        if (!reportIds_.Equals(other.reportIds_)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (TargetPlayerId.Length != 0) hash ^= TargetPlayerId.GetHashCode();
        if (ReportType != 0) hash ^= ReportType.GetHashCode();
        hash ^= reportIds_.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (TargetPlayerId.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(TargetPlayerId);
        }
        if (ReportType != 0)
        {
            output.WriteRawTag(0x10);
            output.WriteInt32(ReportType);
        }
        reportIds_.WriteTo(output, _repeated_reportIds_codec);
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (TargetPlayerId.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(TargetPlayerId);
        }
        if (ReportType != 0)
        {
            size += CodedOutputStream.ComputeTagSize(2);
            size += CodedOutputStream.ComputeInt32Size(ReportType);
        }
        size += reportIds_.CalculateSize(_repeated_reportIds_codec);
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(PlayerReportRequest? other)
    {
        if (other == null) return;
        if (other.TargetPlayerId.Length != 0) TargetPlayerId = other.TargetPlayerId;
        if (other.ReportType != 0) ReportType = other.ReportType;
        reportIds_.Add(other.reportIds_);
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    TargetPlayerId = input.ReadString();
                    break;
                case 16u:
                    ReportType = input.ReadInt32();
                    break;
                case 24u:
                case 26u:
                    reportIds_.AddEntriesFrom(input, _repeated_reportIds_codec);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
