// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Circle;

public sealed partial class EditCircleResponse : IMessage<global::App.Protobuf.Circle.EditCircleResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Circle.EditCircleResponse> _parser = new(() => new global::App.Protobuf.Circle.EditCircleResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Circle.EditCircleResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public EditCircleResponse()
    {
    }

    public EditCircleResponse(EditCircleResponse other) : this() =>
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);

    public EditCircleResponse Clone() => new(this);

    public override bool Equals(object? other) => Equals(other as EditCircleResponse);

    public bool Equals(EditCircleResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode() => _unknownFields?.GetHashCode() ?? 1;
    public override string ToString() => base.ToString() ?? string.Empty;
    public void WriteTo(CodedOutputStream output) => _unknownFields?.WriteTo(output);
    public int CalculateSize() => _unknownFields?.CalculateSize() ?? 0;

    public void MergeFrom(EditCircleResponse? other)
    {
        if (other == null) return;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        while (input.ReadTag() != 0)
            _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
    }
}
