// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Circle;

public sealed partial class RemovePlayerRequest : IMessage<global::App.Protobuf.Circle.RemovePlayerRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Circle.RemovePlayerRequest> _parser = new(() => new global::App.Protobuf.Circle.RemovePlayerRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Circle.RemovePlayerRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public RemovePlayerRequest() { }

    public RemovePlayerRequest(RemovePlayerRequest other) : this()
    {
        playerId_ = other.playerId_;
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public RemovePlayerRequest Clone() => new(this);

    public const int PlayerIdFieldNumber = 1;
    private string playerId_ = "";
    public string PlayerId
    {
        get => playerId_;
        set => playerId_ = value ?? "";
    }

    public override bool Equals(object? other) => Equals(other as RemovePlayerRequest);

    public bool Equals(RemovePlayerRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        return PlayerId == other.PlayerId && Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (PlayerId.Length != 0)
        {
            output.WriteRawTag(0x0A);
            output.WriteString(PlayerId);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (PlayerId.Length != 0)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeStringSize(PlayerId);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(RemovePlayerRequest? other)
    {
        if (other == null) return;
        if (other.PlayerId.Length != 0) PlayerId = other.PlayerId;
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u) PlayerId = input.ReadString();
            else _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        }
    }
}
