// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Circle;

public sealed partial class SearchRequest : IMessage<global::App.Protobuf.Circle.SearchRequest>
{
    private static readonly MessageParser<global::App.Protobuf.Circle.SearchRequest> _parser = new(() => new global::App.Protobuf.Circle.SearchRequest());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Circle.SearchRequest> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public SearchRequest()
    {
    }

    public SearchRequest(SearchRequest other) : this()
    {
        options_ = other.options_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public SearchRequest Clone() => new(this);

    public const int OptionsFieldNumber = 1;
    private global::App.Protobuf.Entity.SearchOptions? options_;
    public global::App.Protobuf.Entity.SearchOptions? Options
    {
        get => options_;
        set => options_ = value;
    }

    public override bool Equals(object? other) => Equals(other as SearchRequest);

    public bool Equals(SearchRequest? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(Options, other.Options)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (Options != null) hash ^= Options.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (Options != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(Options);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (Options != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(Options);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(SearchRequest? other)
    {
        if (other == null) return;
        if (other.Options != null)
        {
            if (Options == null)
                Options = other.Options.Clone();
            else
                Options.MergeFrom(other.Options);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            switch (tag)
            {
                case 10u:
                    Options ??= new global::App.Protobuf.Entity.SearchOptions();
                    input.ReadMessage(Options);
                    break;
                default:
                    _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
            }
        }
    }
}
