// <auto-generated />
#nullable enable

using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace App.Protobuf.Circle;

public sealed partial class UpdateCircleTopResponse : IMessage<global::App.Protobuf.Circle.UpdateCircleTopResponse>
{
    private static readonly MessageParser<global::App.Protobuf.Circle.UpdateCircleTopResponse> _parser = new(() => new global::App.Protobuf.Circle.UpdateCircleTopResponse());
    private UnknownFieldSet? _unknownFields;

    public static MessageParser<global::App.Protobuf.Circle.UpdateCircleTopResponse> Parser => _parser;
    public static MessageDescriptor Descriptor => null!;
    MessageDescriptor IMessage.Descriptor => Descriptor;

    public UpdateCircleTopResponse() { }

    public UpdateCircleTopResponse(UpdateCircleTopResponse other) : this()
    {
        circleTop_ = other.circleTop_?.Clone();
        _unknownFields = UnknownFieldSet.Clone(other._unknownFields);
    }

    public UpdateCircleTopResponse Clone() => new(this);

    public const int CircleTopFieldNumber = 1;
    private global::App.Protobuf.Entity.UpdateCircleTop? circleTop_;
    public global::App.Protobuf.Entity.UpdateCircleTop? CircleTop
    {
        get => circleTop_;
        set => circleTop_ = value;
    }

    public override bool Equals(object? other) => Equals(other as UpdateCircleTopResponse);

    public bool Equals(UpdateCircleTopResponse? other)
    {
        if (ReferenceEquals(other, null)) return false;
        if (ReferenceEquals(other, this)) return true;
        if (!Equals(CircleTop, other.CircleTop)) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    public override int GetHashCode()
    {
        var hash = 1;
        if (CircleTop != null) hash ^= CircleTop.GetHashCode();
        if (_unknownFields != null) hash ^= _unknownFields.GetHashCode();
        return hash;
    }

    public override string ToString() => base.ToString() ?? string.Empty;

    public void WriteTo(CodedOutputStream output)
    {
        if (CircleTop != null)
        {
            output.WriteRawTag(0x0A);
            output.WriteMessage(CircleTop);
        }
        _unknownFields?.WriteTo(output);
    }

    public int CalculateSize()
    {
        var size = 0;
        if (CircleTop != null)
        {
            size += CodedOutputStream.ComputeTagSize(1);
            size += CodedOutputStream.ComputeMessageSize(CircleTop);
        }
        if (_unknownFields != null) size += _unknownFields.CalculateSize();
        return size;
    }

    public void MergeFrom(UpdateCircleTopResponse? other)
    {
        if (other == null) return;
        if (other.CircleTop != null)
        {
            if (CircleTop == null)
                CircleTop = other.CircleTop.Clone();
            else
                CircleTop.MergeFrom(other.CircleTop);
        }
        _unknownFields = UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    public void MergeFrom(CodedInputStream input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if (tag == 10u)
            {
                CircleTop ??= new global::App.Protobuf.Entity.UpdateCircleTop();
                input.ReadMessage(CircleTop);
            }
            else
            {
                _unknownFields = UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
        }
    }
}
